retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Organization_Type__c</fullName>
        <label>Organization Type</label>
        <picklist>
            <picklistValues>
                <fullName>Federal Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>For Profit Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher Education Organization - Private</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher Education Organization - State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HQ Internal Organizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indian Tribe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - County</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - Municipal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Local Government - Township</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National non-profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Profit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Commission</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Education Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U.S. Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unknown Designation</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area_of_Expertise__c</fullName>
        <label>Area of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilitator/Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expertise__c</fullName>
        <label>Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>Collaborated or partnered with one or more service programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service program funded by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service program funded by a non-governmental organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service program funded by a state or local government agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service-learning program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participated in a service or service-learning program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Education &amp; Literacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After School Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Civic Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community-Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Literacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (Higher Ed.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (K-12)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elementary Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/teacher professional development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Work Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head Start/School Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Learning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring &amp; Child Literacy - Elementary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring &amp; Child Literacy - High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring &amp; Child Literacy - Middle School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clean Energy Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Restoration/Clean Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Conservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waste Reduction/Management/Recycling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wildlife, Land, Vegetation Protection/Restoration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Education__c.object
<CustomObject>
    <fields>
        <fullName>Area_s_of_Study_Degree_Details__c</fullName>
        <label>Area(s) of Study/Degree Details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>College_University__c</fullName>
        <inlineHelpText>CNCS staff uses the information in the following sections to determine eligibility to become a Review Participant, so be as comprehensive as possible.</inlineHelpText>
        <label>College/University</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Degree_Earned__c</fullName>
        <label>Degree Earned</label>
        <picklist>
            <picklistValues>
                <fullName>Associate Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bachelor&apos;s Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Master&apos;s Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctorate Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Highest_Level_of_Education__c</fullName>
        <label>Highest Level of Education</label>
        <picklist>
            <picklistValues>
                <fullName>High School Diploma/GED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associates Degree (AA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Degree (e.g. MA, PhD, MD, JD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical School/ Apprenticeship/ Vocational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization_Type__c</fullName>
        <label>Organization Type</label>
        <picklist>
            <picklistValues>
                <fullName>Higher Learning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical/Vocational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User_Account__c</fullName>
        <label>User Account</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Education</relationshipLabel>
        <relationshipName>Education</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Education</label>
    <nameField>
        <label>Education</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Employment__c.object
<CustomObject>
    <fields>
        <fullName>Area_of_Expertise__c</fullName>
        <label>Area of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilitator/Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Organization_Type__c</fullName>
        <label>Organization Type</label>
        <picklist>
            <picklistValues>
                <fullName>City-Wide Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community-Based Nonprofit Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faith-Based Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Higher Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K-12: Elementary School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K-12:  High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>K-12:  Middle School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Municipal Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Foundation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State Agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State-Wide Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VOAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Secondary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical/Vocational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User_Account__c</fullName>
        <label>User Account</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Employment</relationshipLabel>
        <relationshipName>Employment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Employment</label>
    <nameField>
        <label>Employer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/ContactCreateController3.cls
public with sharing class ContactCreateController3 {



    public ContactCreateController3(ApexPages.StandardController controller) {
        
        con = new contact();
        edu = new Education__c();
        emp= new Employment__c();
        attach = new Attachment(); 
        // Add more Contact to account
         abool =false;
         empbool =false;
         edubool =false;
    
        contacts = (Contact)controller.getRecord();
        delattendeeList = new List<Education__C>();
        delattendees = new List<Education__C>();
         //Ends here
        
    }
    
public ID acctID{get;set;}
public ID contactID{get;set;}
public string lastname{get;set;}
public Education__C edu{get;set;}
public contact con{get;set;}
public Employment__c emp{get;set;}
public string accname{get;set;}
public Attachment attach{get; set;}  
public List<Attachment> attachList {get; set;}
// Add more Contact to account

public Account accounts;
public Contact contacts;
public Education__c del;
public Employment__c empdel;
public boolean button_flag=false;
public boolean edubutton_flag=false;
public boolean empbutton_flag=false;
public List<Education__c> addattendeeList {get;set;}
public List<Employment__c> empaddattendeeList {get;set;}
public List<Education__c> delattendeeList {get;set;}
public List<Employment__c> empdelattendeeList {get;set;}
public List<Education__c> attendeeList {get;set;}
public List<Employment__c> empattendeeList {get;set;}
public Integer totalCount {get;set;}
public Integer totalCount1 {get;set;}
public Integer rowIndex {get;set;}
public boolean abool{get;set;}
public boolean edubool{get;set;}
public boolean empbool {get;set;}


public List<Education__c> delAttendees {get; set;} 
public List<Employment__c> empdelAttendees {get; set;} 
//Ends here

   public pagereference save(){
       
    insert con;
    button_flag = true;
    
    return null;
       
   }
   
   // Add more Contact to account
    public void addRow()   // add row for education history
    {

       save(); 
       button_flag = true;
       edubool =true;
       attendeeList = [Select Highest_Level_of_Education__c, College_University__c,Organization_Type__c, Degree_Earned__c , From__c ,To__c,Area_s_of_Study_Degree_Details__c from Education__c where User_Account__c =: con.Id ];
       system.debug('attendeelist size'+attendeeList );
       totalCount = attendeeList.size();
       attendeeList.add(new Education__C(User_Account__c = con.Id));
       system.debug('attendeelist aftersize'+attendeeList );
          
    }
     public void EmpaddRow() // add row for employee history
    {
       system.debug('contact ID'+con.Id );
       if(con.id!=null)
       {
       button_flag = true;
       empbool = true;
       empattendeeList = [Select Area_of_Expertise__c,Experience_Type__c, Expertise__c, From__c , Organization_Type__c ,Job_Description__c,To__c,User_Account__c,Years_of_Experience__c  from Employment__c where User_Account__c =: con.Id ];
       system.debug('attendeelist size'+empattendeeList );
       totalCount1 = empattendeeList.size();
       empattendeeList.add(new Employment__c(User_Account__c = con.Id));
       system.debug('attendeelist aftersize'+empattendeeList );  
       }
       else
       {
       insert con;
       button_flag = true;
       empbool = true;
       empattendeeList = [Select Area_of_Expertise__c,Experience_Type__c, Expertise__c, From__c , Organization_Type__c ,Job_Description__c,To__c,User_Account__c,Years_of_Experience__c  from Employment__c where User_Account__c =: con.Id ];
       system.debug('attendeelist size'+empattendeeList );
       totalCount1 = empattendeeList.size();
       empattendeeList.add(new Employment__c(User_Account__c = con.Id));
       system.debug('attendeelist aftersize'+empattendeeList );
          
       }
           
       
       
    }
    public void deleteRow() // delete row from education history
    {
 
        rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
        System.debug('rowbe deleted ' + rowIndex );
        System.debug('rowm to be deleted '+attendeeList[rowIndex]);
        del = attendeeList.remove(rowIndex);
        delattendeeList.add(del);
 
    }
    public void empdeleteRow() // delete row from employee history
    {
 
        rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
        System.debug('rowbe deleted ' + rowIndex );
        System.debug('rowm to be deleted '+empattendeeList[rowIndex]);
        
        empdel = empattendeeList.remove(rowIndex);
        empdelattendeeList.add(empdel);
 
    }
    public PageReference ave()
    {

        upsert attendeeList;
        delete delattendeeList;
        delete delattendeeList;
        delete empdelattendeeList;
        return (new ApexPages.StandardController(accounts)).view();
    } 
    
     
     //Save all the data to contact,education and employee object
    public pagereference save_upsert(){
           
      
       system.debug('button flag'+button_flag);
       if(button_flag)
       {
            System.debug('edubool  @@@@@@@'+edubool );  
            if(edubool == true || edubool == false)
            {
        
                    //System.debug('attendeeList size @@@@@@@'+attendeeList.size());
                 
                    if(attendeeList != null )
                    {
                    edu.User_Account__c = con.id;
                    system.debug('Contact id-->'+edu.User_Account__c);
                    insert edu;
                    insert attendeeList;    
                    }
                    
                    else
                    {
                    edu.User_Account__c = con.id;
                    system.debug('Contact id-->'+edu.User_Account__c);
                    insert edu;
                        
                    }
            }
           System.debug('empbool  @@@@@@@'+empbool );
           if(empbool == true || empbool == false)
            {
                  //  System.debug('empattendeeList size @@@@@@@'+empattendeeList.size());
                    if( empattendeeList!=null )
                    {
                    emp.User_Account__c= con.id;
                    system.debug('Contact id-->'+emp.User_Account__c);        
                    insert emp; 
                    insert empattendeeList; 
                    }       
                    
                    else
                    {
                    emp.User_Account__c= con.id;
                    system.debug('Contact id-->'+emp.User_Account__c);        
                    insert emp; 
                    }
            }
                attachList = new List<Attachment>();       
                attachList.add(new Attachment(parentId = con.id, name= attach.name, body= attach.body));
                insert attachList;
                System.debug('attachList list @@@@@@@'+attachList);
       }
       else
       {
            insert con;
            button_flag = false;
            edu.User_Account__c = con.id;
            system.debug('Contact id-->'+edu.User_Account__c);
            insert edu;

            emp.User_Account__c= con.id;
            system.debug('Contact id-->'+emp.User_Account__c);        
            insert emp;
             
           
           
            attachList = new List<Attachment>();       
            attachList.add(new Attachment(parentId = con.id, name= attach.name, body= attach.body));
            System.debug('attachList list @@@@@@@'+attachList);
            System.debug('empattendeeList list @@@@@@@'+empattendeeList);
            insert attachList;
            //insert empattendeeList;   
              
       }
        PageReference pageref = new PageReference('/'+con.id);
        return pageref ;
       
   }
   
   
  }