retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EIN__c</fullName>
        <label>EIN</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Legal_Name__c</fullName>
        <label>Legal Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>If your rate has been issued by a state agency, select the stateissuing agency as it is written on the indirect cost rate document.</inlineHelpText>
        <label>State</label>
        <picklist>
            <controllingField>Rate_Type__c</controllingField>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>organization</fullName>
        <active>true</active>
        <label>organization</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>This field stores the first name of the user.</description>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/searchOrganizationcls.cls
public class searchOrganizationcls{
    public Account actobj{get;set;}
    public List<Account> accountList{get;set;}
    public integer actcount{get;set;}
    public String MyAccountId {get; set;}   
    public string userId = ApexPages.currentPage().getParameters().get('uid');
    public searchOrganizationcls(){
        accountList = new List<Account>();
        actobj = new Account();
        actcount = 0;
    }
    public void searchOrganization(){
        String query ='select id,Name,EIN__c,Legal_Name__c,First_Name__c,Address_1__c,City__c,state__c from Account where id!=null';
        if(actObj.EIN__c!=null && actObj.EIN__c!=''){
            query+=' and EIN__c=\''+actObj.EIN__c+'\'';
            accountList=database.query(query);
            if(accountList.size()==0){
            	ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'EIN does not exist in system. Please create a new organization'));
            }
            actcount = accountList.size();
        }
        else{
            actcount = 0;
        }
        System.debug(query);
    
    }


    public pagereference choose(){
    
        Contact newContact =[Select id,AccountId from Contact where Id =:userId limit 1];
        newContact.AccountId = MyAccountId;
        update newContact;
        return new pagereference('/apex/CommunitiesSelfRegConfirm');
    }

    public pagereference registration(){
    
        return null;
    }
    public pagereference createOrganization(){
        return new Pagereference('/apex/Createorganization?uid='+userId);
    }
     public pagereference cancel(){
    
        return new Pagereference('/apex/Login_Page');
    }
    
}