retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Draft__c</fullName>
        <label>Draft</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Draft__c</fullName>
        <label>Draft</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Prefix__c</fullName>
        <label>Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/Draft1.cls
public class Draft1 
{
    Public Application3__c applicationInput{get;set;}
    Public Id tempid;
    public boolean isDraft{get;set;}
    public Draft1 (ApexPages.StandardController controller) 
    {
        isDraft = false;
    applicationInput= new Application3__c();
    tempid=controller.getRecord().id;
    
    }
   Public PageReference SaveAsDraft(){
     //account.Draft__c='true';
     isDraft = true;
     
         try{
             upsert applicationInput;
             PageReference pg = new ApexPages.StandardController(applicationInput).view();
             pg.setRedirect(true);
             return pg;
            }
         Catch(DMLException e){
             return null;
         }
        
       }
   public PageReference MainSave(){
   
     applicationInput.Draft__c='False';
         try{
             if(!validate())
             return null;
             else
             {upsert applicationInput;
             PageReference pg = new ApexPages.StandardController(applicationInput).view();
             pg.setRedirect(true);
             return pg;
           }}
         Catch(DMLException e){
             return null;
         }
    
     }
     
     public boolean Validate()
     {
             if(applicationInput.Prefix__c == null || applicationInput.Prefix__c=='') 
         {
             applicationInput.Prefix__c.addError('You must enter Prefix');
           
             return false;
         }
         else
            return true;
     }
}