retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Applicant_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant/User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Capacity_Building_CP__c</fullName>
        <description>This field is for Concept Paper type of Application.</description>
        <label>Capacity Building</label>
        <picklist>
            <picklistValues>
                <fullName>Capacity Building &amp; Leverage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Effectiveness &amp; Efficiency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scale/Reach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <formula>NOFA_RFP__r.Corporate_Program__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Corporate Program</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disaster_Services_CP__c</fullName>
        <description>This field is for Concept Paper type of Application.</description>
        <label>Disaster Services</label>
        <picklist>
            <picklistValues>
                <fullName>Disaster Assistance Provided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Economic_Opportunities_CP__c</fullName>
        <description>This field is for Concept Paper type of Application.</description>
        <label>Economic Opportunities</label>
        <picklist>
            <picklistValues>
                <fullName>Asset Building</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Economic Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Literacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Find Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Micro-enterprise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Education_CP__c</fullName>
        <description>This field is for Concept Paper type of Application.</description>
        <label>Education</label>
        <picklist>
            <picklistValues>
                <fullName>K-12 Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-HS Education Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Readiness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Teacher Corps</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Energy_Efficiency_CP__c</fullName>
        <label>Energy Efficiency</label>
        <picklist>
            <picklistValues>
                <fullName>Green Jobs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Healthy_Futures_CP__c</fullName>
        <label>Healthy Futures</label>
        <picklist>
            <picklistValues>
                <fullName>Access to Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aging in Place</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>NCCC_Dates_CP__c</fullName>
        <description>This field is for the Concept Paper type of Application.</description>
        <label>NCCC Dates</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <label>Standard 424</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CNCS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Capacity_Building_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Capacity Building</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Corporate_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Corporate Program Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>NOFAs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disaster_Services_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Disaster Services</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Economic_Opportunities_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Economic Opportunities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Education_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Education</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Energy_Efficiency_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Energy Efficiency</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Environmental_Stewardship_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Environmental Stewardship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluation_Summary_or_Plan_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Evaluation Summary or Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Healthy_Futures_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Healthy Futures</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NCCC_Dates_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field shows up on the Concept Paper.</description>
        <label>NCCC Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NCCC_Dates_and_Questions__c</fullName>
        <defaultValue>false</defaultValue>
        <label>NCCC Dates and Questions</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Design_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Program Design</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Management_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field determines which field should show up on the Concept Paper.</description>
        <label>Program Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Proposed_Dates__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Proposed Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Safety_and_Security_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Safety and Security</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Standard 424</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_CP__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Standard</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Set up in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review in Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Tools_and_Equipment_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Tools and Equipment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Veterans_Military_Families_CP__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check box for Concept Paper setup on NOFA.</description>
        <label>Veterans &amp; Military Families</label>
        <type>Checkbox</type>
    </fields>
    <label>NOFA/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFA/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFAs/RFPs</pluralLabel>
    <recordTypes>
        <fullName>NOFA</fullName>
        <active>true</active>
        <label>NOFA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/NOFAtoConceptPaperUIExt.cls
public with sharing class NOFAtoConceptPaperUIExt 
{
    Public Application3__c applicationInput{get;set;}
    Public Id tempid;
    Public String rectype{get;set;}
    Public String rectypename{get;set;}
    public boolean isDraft{get;set;}
    public String id;
    public Boolean displayMsg{get;set;}
    Public NOFA__c Nofa{get;set;}
    public list<selectOption> availableList {get;set;}     
    public list<selectOption> chosenList {get;set;}
    
    //public NOFAtoConceptPaperUIExt handle{get{return this;}}
    
    public NOFAtoConceptPaperUIExt getThis(){
        return this;
    }
    
    
    public NOFAtoConceptPaperUIExt (ApexPages.StandardController controller) 
    {
    
        chosenList =  new list<SelectOption>();
        isDraft = false;
        applicationInput= new Application3__c();
        displayMsg=False;
        tempid=controller.getRecord().id;
        id=Apexpages.currentPage().getParameters().get('id');
        String projectid = Apexpages.currentPage().getParameters().get('projectid'); 
        System.debug('Valueofid'+id);
        applicationInput.Project__c=projectid;        
        applicationInput.NOFA_RFP__c=id;
          applicationInput.Grantee_Status__c='In Progress';
        applicationInput.Applicant_User__c = Userinfo.getUserId();
        If(id!=null && id!='')
           Nofa=[Select NCCC_Dates_CP__c,Proposed_Dates__c,NCCC_Dates_and_Questions__c,Standard_CP__c,Energy_Efficiency_CP__c,Corporate_Program__c,Education_CP__c,Safety_and_Security_CP__c,Tools_and_Equipment_CP__c,Evaluation_Summary_or_Plan_CP__c,Veterans_Military_Families_CP__c,Disaster_Services_CP__c,
                Healthy_Futures_CP__c,Environmental_Stewardship_CP__c,Capacity_Building_CP__c,Economic_Opportunities_CP__c
                ,Standard_424__c,Standard__c,Program_Design_CP__c, Program_Management_CP__c, Recruitment_and_Development_CP__c, Strengthening_Communities_CP__c, Amendment_Justification_CP__c, 
                Other_CP__c, Continuation_Changes_CP__c, Clarification_Summary_CP__c, Cost_Effectiveness_and_Budget_Adequacy_C__c, Organizational_Capability_CP__c, Need_CP__c,
                Intermediary_Justification_CP__c, Executive_Summary_CP__c, Focus_Areas_and_Objectives_NCCC_CP__c, Target_Populations_CP__c,
                Have_funding_history_with_a_CNCS_Prog_CP__c, Other_NCCC_CP__c,
                Safety_and_Security_AP__c,Review_Cycle__c  from NOFA__c where id=:id];
           // System.debug('Valueofid'+id+'$$$$$'+Nofa.Foster_Grandparents_Only__c);        
        rectype=[Select id,name from Recordtype where SObjectType='Application3__c' and name='Concept Paper'].id;
     }
  
   
     Public PageReference SaveAsDraft(){
         PageReference Redirect;
         //handle.chosenList = selectedOptions;
        
         system.debug('chosen list = '+chosenList);  
         try{
            applicationInput.recordtypeid=rectype;
            applicationInput.NOFA_RFP__c=id;
            insert applicationInput;
            Redirect = new PageReference('/'+applicationInput.id);
             
            return Redirect;
            }
         Catch(DMLException e){
             System.debug('@@@@@@@@!!!!!'+e.getmessage());
         }
  
         return null; 
         
       } 
      
      
      
        public pagereference createProject(){
             return new Pagereference('/a0W/e?retURL=%2Fa0W%2Fo');
        }     
   
   public PageReference save1(){
   	
   		 map<String,Boolean> checkRequiredNarrativeFields = new map<String,Boolean>();
        
         PageReference Redirect;
         try{
             if(!validate()) {
             ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Concept Paper cannot be Submitted, Due to the following reason: Please enter atleast 1 value for Focus Area and Objectives:'));
             
             	return null; 
             }
             checkRequiredNarrativeFields = ApplicationCheck.checkCPNarrativeFields(applicationInput,applicationInput.NOFA_RFP__c);
        	 if(checkRequiredNarrativeFields.size()>0){
                string fieldNames = '';
                for(String fieldName: checkRequiredNarrativeFields.keyset()){
                   fieldNames += fieldName +', ';
                }
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Concept Paper cannot be Submitted, Due to the following reason: Please enter values for Narrative fields: '+fieldNames));
                  return null;
             }
             
             if(Nofa.Review_Cycle__c == 'Rolling'){
                applicationInput.Grantee_Status__c = 'Submitted';
                applicationInput.Status__c = 'Submitted';
              }
              else if(Nofa.Review_Cycle__c == 'Post-Deadline'){
                applicationInput.Grantee_Status__c = 'Pre - Submitted';
                applicationInput.Status__c = 'Pre - Submitted';
              }
             applicationInput.recordtypeid=rectype;
             applicationInput.NOFA_RFP__c=id;
             Insert applicationInput;
             Redirect = new PageReference('/'+applicationInput.id);
             return Redirect;
         }
         Catch(DMLException e){
             System.debug('@@@@@@@@!!!!!'+e.getmessage());
         }
             return null;
         }
         
    public boolean Validate()
    {	
    	 if(Nofa.Education_CP__c == true || Nofa.Veterans_Military_Families_CP__c == true || Nofa.Energy_Efficiency_CP__c == true || Nofa.Healthy_Futures_CP__c == true || Nofa.Economic_Opportunities_CP__c == true || Nofa.Disaster_Services_CP__c == true || Nofa.Environmental_Stewardship_CP__c == true || Nofa.Capacity_Building_CP__c == true || Nofa.Focus_Areas_and_Objectives_NCCC_CP__c == true ){
    	 	
    	 	if(applicationInput.Education_CP__c == null && applicationInput.Veterans_and_Military_Families_CP__c == null && applicationInput.Energy_Efficiency_CP__c == null && applicationInput.Healthy_Futures_CP__c == null && applicationInput.Economic_Opportunities_CP__c == null && applicationInput.Disaster_Services_CP__c == null && applicationInput.Environment_Stewardship_CP__c == null && applicationInput.Capacity_Building_CP__c == null
    	 	&& applicationInput.Natural_and_Other_Disasters_CP__c == null && applicationInput.Environmental_Stewardship_Conservation_C__c == null && applicationInput.Energy_Conservation_CP__c == null && applicationInput.Infrastructure_Improvement_CP__c == null && applicationInput.Urban_and_Rural_Development_CP__c == null){
    	 		return false;
    	 	}
    	 }
    	 return true;
    	 
         /*if(applicationInput.Education_CP__c == null && (Nofa.Education_CP__c==True))
         {
             applicationInput.Education_CP__c.addError('You must enter Education');
           return false; 
         }
         else if (applicationInput.Healthy_Futures_CP__c == null && Nofa.Healthy_Futures_CP__c==True)
         {
         applicationInput.Healthy_Futures_CP__c.addError('You must enter Health');
         return false;
         }
                        
             else
            return true;
    	}*/
    }

 }