retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Amendment_Justification__c</fullName>
        <label>Amendment Justification</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Clarification_Summary__c</fullName>
        <label>Clarification Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Continuation_Changes__c</fullName>
        <label>Continuation Changes</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Cost_Effectiveness_and_Budget_Adequacy__c</fullName>
        <label>Cost Effectiveness and Budget Adequacy</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executive_Summary__c</fullName>
        <label>Executive Summary</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Intermediary_Justification__c</fullName>
        <label>Intermediary Justification</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Leadership_and_Team__c</fullName>
        <label>Leadership and Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Need__c</fullName>
        <label>Need</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizational_Capability__c</fullName>
        <label>Organizational Capability</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <label>Other</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program_Design__c</fullName>
        <label>Project Design</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Program_Management__c</fullName>
        <label>Project Management</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruitment_and_Development__c</fullName>
        <label>Recruitment and Development</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <label>Standard 424</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities__c</fullName>
        <label>Strengthening Communities</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary_of_Accomplishments__c</fullName>
        <label>Summary of Accomplishments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VISTA_Assignment__c</fullName>
        <label>VISTA Assignment</label>
        <length>50000</length>
        <type>Html</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Allow_Concept_Paper__c</fullName>
        <label>Require Concept Paper</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Amendment_Justification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Amendment Justification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Clarification_Summary__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clarification Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Continuation_Changes__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Continuation Changes</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cost_Effectiveness_and_Budget_Adequacy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cost Effectiveness and Budget Adequacy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Evaluation_Summary_of_Plan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Evaluation Summary of Plan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Executive_Summary__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Executive Summary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Foster_Grandparents_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Foster Grandparents Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intermediary_Justification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intermediary Justification</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Leadership_and_Team__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Leadership and Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Need__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Need</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>NOFAs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizational_Capability__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Organizational Capability</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Other__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Other</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Design__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Design</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Management__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Project Management</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If your project is not found then add a new project under your Account.</inlineHelpText>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>NOFAs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSVP_Only__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RSVP Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Recruitment_and_Development__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Recruitment and Development</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Standard_424__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Standard 424</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Strengthening_Communities__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Strengthening Communities</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary_of_Accomplishments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Summary of Accomplishments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VISTA_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>VISTA Assignment</label>
        <type>Checkbox</type>
    </fields>
    <label>NOFA/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFA/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFAs/RFPs</pluralLabel>
    <recordTypes>
        <fullName>NOFA</fullName>
        <active>true</active>
        <label>NOFA</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Organization__c.object
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/NOFAtoApplicationUIExt2.cls
public class NOFAtoApplicationUIExt2 
{
    Public Application3__c applicationInput{get;set;}
    Public id tempid;
    public String id;
    public String projectid; 
    public boolean isDraft{get;set;}
     Public NOFA__c Nofa{get;set;}
     Project__c pro{get;set;}
     
    public NOFAtoApplicationUIExt2 (ApexPages.StandardController controller) 
  
    {
        isDraft = false;
    applicationInput= new Application3__c();
    system.debug('params = '+Apexpages.currentPage().getParameters());
    tempid=controller.getRecord().id;
     id=Apexpages.currentPage().getParameters().get('id');
    projectid=Apexpages.currentPage().getParameters().get('projectid');
    System.debug('Valueofid'+id+'*****'+projectid);
   //  applicationInput.Project__c=projectid; 
     If(id!=null && id!='')
      Nofa=[Select ID,Allow_Concept_Paper__c,Intermediary_Justification__c,Need__c,Clarification_Summary__c,Continuation_Changes__c,VISTA_Assignment__c,Project_Name__c,Summary_of_Accomplishments__c,Leadership_and_Team__c,Cost_Effectiveness_and_Budget_Adequacy__c,Organizational_Capability__c,Executive_Summary__c,Other__c,Amendment_Justification__c,Strengthening_Communities__c,Recruitment_and_Development__c,Foster_Grandparents_Only__c,Evaluation_Summary_of_Plan__c,Standard_424__c,Program_Design__c,Program_Management__c,RSVP_Only__c from NOFA__c where id=:id];
        System.debug('Valueofid'+id+'$$$$$'+Nofa.Foster_Grandparents_Only__c);   
        applicationInput.NOFA_RFP__c=id;    
      //  applicationInput.Project__c=projectid; 
  }
   
   Public PageReference Apply(){
   projectid=applicationInput.Project__c;
   If(Nofa.Allow_Concept_Paper__c == 'Yes'){
   //    PageReference Redirect;

  //  return new Pagereference('/apex/ApplicationUI?id='+id+'&%retURL='+projectid);
     
     return new Pagereference('/apex/NOFAtoConceptPaperUI?id='+id+'&projectid='+projectid);}
     else
     {
        if(Apexpages.currentPage().getParameters().get('submittedLate')!=null){
             return new Pagereference('/apex/NOFAtoApplicationUI?id='+id+'&projectid='+projectid+'&submittedLate=Yes');
        }else{
            return new Pagereference('/apex/NOFAtoApplicationUI?id='+id+'&projectid='+projectid);
        }
     }
     
     
                  /* try{
         applicationInput.NOFA_RFP__c=id;
           
             Redirect =  new Pagereference('/apex/NOFAtoApplicationUI?addto='+id+'&%retURL='+projectid);
             
             return Redirect;
            }
      Catch(DMLException e){
          System.debug('@@@@@@@@!!!!!'+e.getmessage());
}
  */
            
            
              }
   
      
     public pagereference createProject(){
 //PageReference Redirect;
   //  User loggedinUser = [Select name,isPortalEnabled,contactid,contact.AccountId from user where id=:userinfo.getUserId()];
              // if(loggedinUser.isPortalEnabled)
     //         System.debug('$$%$%$$%$%'+contact.AccountId);
       //    pro.Organization__c = loggedinUser.contact.AccountId;
         //    PageReference pageref = new PageReference('/a0W/e?retURL=%2Fa0W%2Fo');
        //return pageref ;
      return new Pagereference('/a0W/e?retURL=%2Fa0W%2Fo');
        
    }
    public pagereference cancel(){
    
        return new Pagereference('/a0A/o');
    }
 }