retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Concept_Paper_Name__c</fullName>
        <label>Concept Paper Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_ID__c</fullName>
        <formula>NOFA_RFP__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFA ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CNCS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Withdraw_Justification__c</fullName>
        <label>Withdraw Justification</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/ConceptPaperEdit.cls
Public Class ConceptPaperEdit{

public Application3__c applicationInput {get; set;}
public Boolean displayMsg{get;set;}
public String id;
public Boolean fieldSet1Visibility {get; set;}
public Boolean fieldSet2Visibility {get; set;}
public Boolean fieldSet3Visibility {get; set;}
public string productType {get;set;}
public list<selectOption> availableList {get;set;}     
public list<selectOption> chosenList {get;set;}

public list<Application3__c> typeOfProduct {get; set;}

Public ConceptPaperEdit(ApexPages.StandardController controller){
  applicationInput=new Application3__c();
  displayMsg=False;
  id=Apexpages.currentPage().getParameters().get('id');
 applicationInput.Status__c= null;
  If(id!=null && id!='')

  applicationInput= [Select id,Status__c,Withdraw_Justification__c,Concept_Paper_Name__c,Grantee_Status__c,NOFA_ID__c FROM Application3__c where id = :id];
  
}

    public PageReference edit() {   
    PageReference Redirect;
    If(id!=null && id!=''){
    Redirect = new PageReference('/apex/ConceptpaperEdit?id='+applicationInput.id);
    system.debug('Redirect id-->'+Redirect);
    return Redirect;
    }
    
    return null;
    }
    
    
    
    public PageReference save() {   
    PageReference Redirect;
    If(id!=null && id!=''){
    Redirect = new PageReference('/apex/ConceptPaperdetail?id='+applicationInput.id);
    applicationInput.Status__c='Submitted';
    update applicationInput;
    //return Redirect;
    }
    else
    {
    
    applicationInput.Status__c='Submitted';
    insert applicationInput;
    system.debug('record id-->'+applicationInput.id);
    
    Redirect = new   PageReference('/apex/ConceptPaperdetail?id='+applicationInput.id);
    Redirect.setRedirect(true);
    //return newpage;
    }
    return Redirect;
    }
    


    Public PageReference SaveAsDraft()
    {
          PageReference Redirect;
        If(id!=null && id!=''){
        Redirect = new PageReference('/apex/ConceptPaperdetail?id='+applicationInput.id);
        applicationInput.Status__c='--None--';      
        update applicationInput;
        System.debug('app;lication values-->'+applicationInput);
       // return Redirect;
        }
        
        else
        {

        applicationInput.Status__c='--None--';
        insert applicationInput;
        system.debug('record id-->'+applicationInput.id);

        Redirect = new   PageReference('/apex/ConceptPaperdetail?id='+applicationInput.id);
        Redirect.setRedirect(true);
        //return newpage;
        }

            
        return Redirect;
          
    }
        
      Public PageReference Reopen()
    {
        
        showPopup(); 
                  
        return null;
          
    }  
    
    Public PageReference withdrawbtn()
    {
           
        showPopup();
                   
        return null;
          
    }  
    
   // Model Pop Code Starts here
   public boolean displayPopup {get; set;}
 
    public void closePopup() {
        displayPopup = false;
    }
 
    public void showPopup() {
        displayPopup = true;
    }
    public PageReference Okbtn() {
    
        PageReference Redirect;
        If(id!=null && id!=''){
        Redirect = new PageReference('/apex/ConceptPaperdetail?id='+applicationInput.id);
        applicationInput.Status__c='Withdraw';
        update applicationInput;
        System.debug('app;lication values-->'+applicationInput);
        //return Redirect;
        }
        return Redirect;
    }
    
     public PageReference ReopenOkbtn() {
         
        PageReference Redirect;
        If(id!=null && id!=''){
        Redirect = new PageReference('/apex/ConceptpaperEdit?id='+applicationInput.id);
        applicationInput.Status__c=null;
        update applicationInput;
        System.debug('app;lication values-->'+applicationInput);
        return Redirect;
        }
            
        return null;
    }
    
    // Pop up code ends here

}