retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <label>NOFA/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFA/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFAs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/RecordTypeExtension1.cls
Public Class RecordTypeExtension1{

public List<Application3__c> applicationLists {get; set;}  
public Application3__c applicationOffice {get; set;}
public Integer size;  
Public String rectype{get;set;}
Public String rectypename{get;set;}
public Boolean displayMsg{get;set;}

Public RecordTypeExtension1(ApexPages.StandardController controller){
  displayMsg=False;
  applicationLists=new List<Application3__c>();
  Application3__c dummyApplication = new  Application3__c();   
  applicationLists.add(dummyApplication); 
  rectype= Apexpages.currentPage().getParameters().get('RecordType');
  
  If(rectype!=null)
  rectypename=[Select name from Recordtype where SObjectType='Application3__c' and id=:rectype].name;
  System.debug('Prashant$$$$$$$'+rectypename);
}

public PageReference addApplication() {    
Application3__c dummyApplication = new  Application3__c();         
applicationLists.add(dummyApplication);        
size = applicationLists.size();        
return null;    
}   

public PageReference save() {   

if(applicationLists.size()>0){       
//List<applicationLists> insertapplicationObj = new List<applicationLists>();  
try{
Insert applicationLists;
}
catch(Exception e){
System.debug('@@@@@@@@!!!!!'+e.getmessage());
}
displayMsg=True;   
System.debug('@@@@@@@@&&&&&&'+displayMsg);
}   
return null;
}
public pagereference createProject(){
        return new Pagereference('/a0W/e?retURL=%2Fa0W%2Fo');
        
    }
    public pagereference cancel(){
    
        return new Pagereference('/a0A/o');
    }
    public pagereference apply(){
     
     return new Pagereference('/apex/ApplicationUI?retURL=%2Fa0V%2Fo&RecordType=012r00000004IJ5?NOFA_RFP__c={!NOFA__c.Id}&Project__c={!Project__c.Name}');
     
    }

}