retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments</description>
        <inlineHelpText>Comments</inlineHelpText>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CNCS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <label>Submitted By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the epert reviewer application</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - SAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Set up in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review in Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFA/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFA/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFAs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/CustomSendEmailController.cls
public with sharing class CustomSendEmailController {
        public String subject { get; set; }    
        public String body { get; set; }  
        public string toAddresses {get;set;}
        public string toCCAddresses {get;set;}
        public User auser {get;set;}
        public Id appId {get;set;}
        public Application3__c app{get;set;}
        public String status{get;set;}
        
        public CustomSendEmailController (){
            String tmpName = ApexPages.CurrentPage().getParameters().get('tmpName');
            toAddresses = ApexPages.CurrentPage().getParameters().get('toAddresses');
            status = ApexPages.CurrentPage().getParameters().get('status');
            appId = ApexPages.CurrentPage().getParameters().get('appId');
            //Application3__c app;
            system.debug('appId = '+appId);
            if(appId!=null){
             app = [Select Id,Name,Submitted_By__c, Comments__c,CreatedById,CreatedBy.Name,Grantee_Status__c,Status__c from Application3__c where Id = :appId];
        	}
        	system.debug('tmpName = '+tmpName);
            EmailTemplate template = [Select Id,Name,Body,Subject from EmailTemplate where DeveloperName = :tmpName];
            subject = template.Subject;            
            body = template.Body; 
            system.debug('createdById = '+app.CreatedById);
            User createdBy = [Select Id,Name from User where Id = :app.CreatedById];  
            system.debug('after user query = '+createdBy);
            if(body.contains('{!User.Name}'))
            	body = (null == app.CreatedById) ? body : body.replace('{!User.Name}',CreatedBy.Name); 
            if(body.contains('{!Application3__c.Comments__c}'))
            	body = (null == app.Comments__c) ? body.replace('{!Application3__c.Comments__c}','') : body.replace('{!Application3__c.Comments__c}',app.Comments__c);  
            if(body.contains('{!NOFA__c.CreatedBy}')){            	           	
            	body = (null == app.CreatedById) ? body : body.replace('{!NOFA__c.CreatedBy}',CreatedBy.Name);   
            }
            	      
        }
        
        public PageReference sendEmails(){
        	Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage(); 
            list<String> addressesToSend = new list<String>();
            list<String> addressesToCC = new list<String>();
            if(toAddresses!=null){
            	addressesToSend.add(toAddresses);
            }
            if(toCCAddresses != null && toCCAddresses !=''){            	
            	addressesToCC = toCCAddresses.split(';');
            }            
            email.setSubject( subject );
            email.setToAddresses( addressesToSend );
            email.setPlainTextBody( body );      
            if(addressesToCC.size()>0){            	
            	email.setCcAddresses(addressesToCC);
            }                                  
            app.Grantee_Status__c = status;
 			app.Status__c = status;      
 			Database.Saveresult appUpdate = Database.update(app);
 			//update app;     
 			if(appUpdate.isSuccess()){
 				try{
 					Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});    
               		//ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Successfully sent email(s) to contacts'));
 				} catch(Exception e){            	
           			 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Unable to send email, please contact your admin'));
           			 return null;
           		}
 			}else{
 				ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error,'Unable to update Concept Paper, please contact your admin'));
 				return null;
 			}           
        	PageReference pg = new PageReference('/'+appId);
        	pg.setRedirect(true);
            return pg;
        }
        
        public PageReference cancel(){
        	 PageReference pg = new PageReference('/'+appId);
        	 system.debug('appId = '+appId);
        	 pg.setRedirect(true);
             return pg;
        }
}