retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Applicant_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant/User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Fiscal_Yr__c</fullName>
        <formula>TEXT( NOFA_RFP__r.Fiscal_Yr__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFA Fiscal Yr</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Name</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Fiscal_Yr__c</fullName>
        <label>Fiscal Yr</label>
        <picklist>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>NOFAs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NOFA/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFA/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFAs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Organization__c.object
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Projects</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/ApplicationHelper.cls
public with sharing class ApplicationHelper {
    public static void checkApplicationforSameYr(list<Application3__c> newApps){
        set<Id> projectIds = new set<Id>();
        set<Id> nofaIds = new set<Id>();
        list<Project__c> projects = new list<Project__c>();              
        Id appRecordTypeId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
        for(Application3__c a: newApps){
        system.debug('newApps= '+newApps);        
          if(a.Project__c != null && appRecordTypeId == a.RecordTypeId){
             projectIds.add(a.Project__c);
          }
        }        
        projects = [Select p.Name, p.Id,p.Organization__c, (Select Id, Name,NOFA_RFP__c,NOFA_RFP__r.Fiscal_Yr__c,NOFA_Fiscal_Yr__c,Project__c From Application__r) From Project__c p where Id in : projectIds];        
        for(Project__c p: projects){            
            if(p.Application__r!=null){
                for(Application3__c a: p.Application__r){
                  if(a.RecordTypeId == appRecordTypeId){
                    nofaIds.add(a.NOFA_RFP__c);
                  }  
                }
                for(Application3__c newApp: newApps){
                    nofaIds.add(newApp.NOFA_RFP__c);
                }
            }
        }
        
       Map<Id,Nofa__c> nofaFiscalYrs = new Map<Id,Nofa__c>([Select Id,Fiscal_Yr__c from NOFA__c where Id in :nofaIds]);      
       
        for(Project__c p: projects){
            
            for(Application3__c newApp: newApps){               
                if(p.Application__r.size()>0){
                    for(Application3__c a: p.Application__r){       
                        if(a.RecordTypeId == appRecordTypeId){                                 
                            if(a.Project__c == newApp.Project__c && a.NOFA_RFP__c == newApp.NOFA_RFP__c && (a.NOFA_Fiscal_Yr__c != '' && a.Nofa_Fiscal_yr__c != null) && a.NOFA_Fiscal_Yr__c == nofaFiscalYrs.get(newApp.NOFA_RFP__c).Fiscal_Yr__c){                           	
                                newApp.adderror('A project can only be attached to a single application in a fiscal year');                           
                        	}
                        }
                     } 
                    
                }
                         
                /*else if(p.Application__r.size() == 0 && p.Organization__c!=null){
                    system.debug('got here 2');
                    Boolean isDupe = isDupeAppWithaDiffProject(p.Organization__c,newApp.NOFA_RFP__c,nofaFiscalYrs.get(newApp.NOFA_RFP__c));
                    if(isDupe){
                        newApp.adderror('A project can only be attached to a single application in a fiscal year');
                    }   
                }*/
            }
        }
        
        
    }    
    
    
    /*public static boolean isDupeAppWithaDiffProject(Id orgId,Id nofaId,String yr){
        set<Id> projectIds = new set<Id>();
        list<Project__c> projects = new list<Project__c>();
        
        Account a = [Select a.Name, a.Id, (Select Name From Projects__r) From Account a where Id = :orgId];
        if(a!=null && a.Projects__r != null){
            for(Project__c p: a.Projects__r){
                projectIds.add(p.Id);
            }   
        }
        system.debug('project Ids = '+projectIds);
        projects = [Select p.Name, p.Id,p.Organization__c, (Select Id, Name,NOFA_RFP__c,NOFA_RFP__r.Fiscal_Yr__c,NOFA_Fiscal_Yr__c,Project__c From Application__r) From Project__c p where Id in : projectIds];        
        
        for(Project__c p: projects){
            if(p.Application__r!=null){
                for(Application3__c app: p.Application__r){                 
                    if(app.Nofa_RFP__c == nofaId && app.NOFA_Fiscal_Yr__c == yr){
                        return true;
                    }
                    
                }
            }
        }
        return false;
        
    }*/
    
    /*public static void populateOrg(list<Application3__c> newapps){
        set<Id> usrIds = new set<Id>();
        map<Id,Id> usrIdtoOrgId = new map<Id,Id>();
        for(Application3__c a: newapps){
            if(a.Applicant_User__c !=null){
                usrIds.add(a.Applicant_User__c);
            } 
        }
        system.debug('usrIds = '+usrIds);
        list<User> users = new list<User>([Select u.Name, u.Id, u.AccountId From User u where Id in :usrIds]);
        for(User u:users){
            if(u.AccountId!=null)
                usrIdtoOrgId.put(u.Id,u.AccountId);
        }
        system.debug('user map = '+usrIdtoOrgId);
        for(Application3__c a:newApps){
            if(usrIdtoOrgId.get(a.Applicant_User__c)!=null){
                a.Organization__c = usrIdtoOrgId.get(a.Applicant_User__c);
            }
        }
        
    }*/
    
}