retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Concept_Paper_Due_Date__c</fullName>
        <description>for Concept Paper Reporting purpose</description>
        <formula>NOFA_RFP__r.Concept_Paper_Due_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Concept Paper Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grantee_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold Pending Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return for Re-work</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <formula>NOFA_RFP__r.NOFA_name__c</formula>
        <label>NOFA Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA_RFP__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA/RFP ID</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>Application</relationshipLabel>
        <relationshipName>Application</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>CNCS Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre - Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected by Prime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted Late to CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <label>Submitted By</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA__c.object
<CustomObject>
    <description>This is the first tab in the CNCS app</description>
    <fields>
        <fullName>Applications_due_date__c</fullName>
        <label>Application Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Concept_Paper_Due_Date__c</fullName>
        <description>Concept Paper Due Date for this NOFA</description>
        <label>Concept Paper Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Fiscal_Yr__c</fullName>
        <label>Fiscal Yr</label>
        <picklist>
            <picklistValues>
                <fullName>2002</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2003</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2004</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2005</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2006</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2007</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2008</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2009</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2010</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2011</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2012</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2013</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2014</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2015</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2016</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2017</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2018</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2019</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2020</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>NOFA_name__c</fullName>
        <label>NOFA Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>NOFAs/RFPs</relationshipLabel>
        <relationshipName>NOFAs_RFPs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Set up in Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review in Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Rework</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalized</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFA/RFP</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>NOFA/RFP ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFAs/RFPs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA_Group__c.object
<CustomObject>
    <fields>
        <fullName>Review_of__c</fullName>
        <label>Review of</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Concept papers</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFA Group</label>
    <nameField>
        <displayFormat>NOFA Group-{0000}</displayFormat>
        <label>NOFA Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFA Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA_Member__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>NOFA Member</relationshipLabel>
        <relationshipName>NOFA_Member</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Name__c</fullName>
        <formula>NOFA__r.NOFA_name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>NOFA Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NOFA__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA</label>
        <referenceTo>NOFA__c</referenceTo>
        <relationshipLabel>NOFA Member</relationshipLabel>
        <relationshipName>NOFA_Member</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NOFA Member</label>
    <nameField>
        <displayFormat>NOFA Member{0000}</displayFormat>
        <label>NOFA Member ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFA Member</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Organization__c.object
<CustomObject>
    <label>Organization</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Organization</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to stages object to the stage number</description>
        <label>Stage Number</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <label>NOFA Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Stages</relationshipLabel>
        <relationshipName>Stages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <label>Stage Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Describes the status of that particular stage</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/CustomLookupController.cls
public with sharing class CustomLookupController {
    
  public Application3__c app{get;set;} // new account to create
  public List<Application3__c> results{get;set;} // search results
  public string searchString{get;set;} // search keyword
  public Id parentId{get;set;}
  static public string sObjType;
  
  public CustomLookupController() {
    Application3__c app = new Application3__c ();
    // get the current search string
    searchString = System.currentPageReference().getParameters().get('lksrch');
    parentId = System.currentPageReference().getParameters().get('parentId');
    system.debug('ParentId = '+parentId);    
    runSearch();  
  }
   
  // performs the keyword search
  public PageReference search() {
    runSearch();
    return null;
  }
  
  // prepare the query and issue the search command
  private void runSearch() {
    // TODO prepare query string for complex serarches & prevent injections
    results = performSearch(searchString);               
  } 
  
  // run the search and return the records found. 
  private List<Application3__c> performSearch(string searchString) {
    
    String soql = 'select id, name '; 
    String soql1 = 'select id, name '; 
    string t1='\'';
  string t2= '\'';
  Id recTypeId = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Application').getRecordTypeId();
  Id recTypeId1 = Schema.SObjectType.Application3__c.getRecordTypeInfosByName().get('Concept Paper').getRecordTypeId();
  String statusofApp = 'Submitted';
  // soql1 = soql1 + ', Nofa_RFP__c, Organization__c, Grantee_Status__c, Status__c, Submitted_By__c from Application3__c where Status__c = '+t1+statusofApp+t2+' and recordTypeId1 = '+t1+recTypeId+t2;

  
    soql = soql + ', Nofa_RFP__c, Organization__c, Grantee_Status__c, Status__c, Submitted_By__c from Application3__c where Status__c = '+t1+statusofApp+t2;      
  
    if(parentId != null){
      sObjType = parentId.getsObjectType().getDescribe().getName();
      system.debug('ParentId in search = '+parentId);
      
      system.debug('got here = '+sObjType);
      /*if(sObjType == 'Nofa_Group__c'){        
          NOFA_Group__c parent = [Select Id,Fiscal_yr__c from  NOFA_Group__c where Id = :parentId];          
          soql = soql + ', NOFA_name__c,Concept_Paper_Due_Date__c,Applications_due_date__c,Fiscal_Yr__c from NOFA__c ';
          if(parent.Fiscal_Yr__c != null && parent.Fiscal_yr__c != '')
              soql = soql + ' where Fiscal_Yr__c = '+t1+parent.Fiscal_yr__c+t2;
      }*/
      if(sObjType == 'Paneling__c'){        
        
        set<Id> nofaIds = new set<Id>();
        Paneling__c parent = [Select Id, Name, Stage_Number__r.NOFA_Group__r.Id from Paneling__c where Id = :parentId];
        if(parent!=null && parent.Stage_Number__r.Nofa_Group__r.Id!=null)
		{
          NOFA_Group__c nfGrp = [Select n.Name, n.Id,Review_of__c, (Select Id, NOFA__c From NOFA_Member__r) From NOFA_Group__c n where Id = :parent.Stage_Number__r.Nofa_Group__r.Id];
          if(nfgrp != null && nfGrp.NOFA_Member__r != null)
				{
					for(NOFA_Member__c nm: nfGrp.NOFA_Member__r)
						{
							nofaIds.add(nm.Nofa__c);
						}
				}			
			 system.debug('size = '+nofaIds.size());
			 if(nofaIds.size()>0)
				{
					if(nfGrp.Review_of__c == 'Application')
					{ 
            
						system.debug('soql = '+soql);
						soql = soql +  ' and NOFA_RFP__c in : nofaIds and recordTypeId = '+t1+recTypeId+t2;
          //  soql1 = soql1 +  ' and NOFA_RFP__c in : nofaIds';
           
							if(searchString != '' && searchString != null)
								{
									soql = soql +  ' and name LIKE \'%' + searchString +'%\'';
								}
							}
						else if(nfGrp.Review_of__c == 'Concept papers')
							{	
								soql = soql +  ' and NOFA_RFP__c in : nofaIds and recordTypeId = '+t1+recTypeId1+t2;																
								if(searchString != '' && searchString != null)
									{
										
										soql = soql +  ' and name LIKE \'%' + searchString +'%\'';
									}
							} 
				}else if(nofaIds.size()==0){
            if(searchString != '' && searchString != null)
				{
                soql = soql +  ' and name LIKE \'%' + searchString +'%\'';
               }
          }
        }
      }        
    }
    if(parentId == null && (searchString != '' && searchString != null)){
      soql = soql +  ' name LIKE \'%' + searchString +'%\'';
    }
    soql = soql + ' limit 25';
    system.debug('soql = '+soql);
    System.debug(soql);
    return database.query(soql); 

  }
  
  /*// save the new account record
  public PageReference saveAccount() {
    insert account;
    // reset the account
    account = new Account();
    return null;
  }*/
  
  // used by the visualforce page to send the link to the right dom element
  public string getFormTag() {
    return System.currentPageReference().getParameters().get('frm');
  }
    
  // used by the visualforce page to send the link to the right dom element for the text box
  public string getTextBox() {
    return System.currentPageReference().getParameters().get('txt');
  }
 
}