retrieveUnpackaged/objects/Application3__c.object
<CustomObject>
    <description>SF-424</description>
    <fields>
        <fullName>Draft__c</fullName>
        <label>Draft</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Applicant__c</fullName>
        <label>Type of Applicant</label>
        <picklist>
            <picklistValues>
                <fullName>State Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>County Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>City or Township Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special District Government</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Regional Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>U.S. Territory or Possession</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Independent School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public/State Controlled Institution of Higher Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indian/Native American Tribal Government (Federally Recognized)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indian/Native American Tribal Government (Other than Federally Recognized)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indian/Native American Tribally Designated Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public/Indian Housing Authority</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nonprofit with 501C3 IRS Status (Other than Institution of Higher Education)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nonprofit without 501C3 IRS Status (Other than Institution of Higher Education)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Private Institution of Higher Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>For-Profit Organization (Other than Small Business)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Small Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hispanic-serving Institution</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Historically Black Colleges and Universities (HBCUs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tribally Controlled Colleges and Universities (TCCUs)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska Native and Native Hawaiian Serving Institutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-domestic (non-US) Entity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other (specify</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>of_bathrooms__c</fullName>
        <label># of bathrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Application</label>
    <nameField>
        <label>Application ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <recordTypes>
        <fullName>Application</fullName>
        <active>true</active>
        <label>Application</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/SaveDraft.cls
public class SaveDraft {
   Public Application3__c application {get;set;}
  Public Id tempid;
  public boolean isSaveDraft{get;set;}
    public SaveDraft (ApexPages.StandardController controller) {
    isSaveDraft = False;
    application= new Application3__c();
    tempid=controller.getRecord().id;
    System.debug('vijay id'+tempid);
   
   
   //if(tempid !=null){
    //Application3__c Temp = [SELECT Id, Type_of_Applicant__c, of_bathrooms__c, Draft__c FROM Application3__c Where Id=:tempid Limit 1];
    // application=Temp;   
     //}            
    
        
    
    }     
    
   
   Public PageReference SaveAsDraft()
   {
     application.Draft__c='true';
     
         try{
             
insert application;
             PageReference pg = new ApexPages.StandardController(application).view();
             pg.setRedirect(true);
             return pg;
            }
         Catch(DMLException e){
             return null;
         }
         
       }
   public PageReference Save(){
   
     application.Draft__c='False';
         try{
             upsert application;
             PageReference pg = new ApexPages.StandardController(application).view();
             pg.setRedirect(true);
             return pg;
           }
         Catch(DMLException e){
             return null;
         }
    
     }
}