retrieveUnpackaged/objects/Application_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application ID</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Application Feedback</relationshipLabel>
        <relationshipName>Application_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expert_Review_Panel__c</fullName>
        <label>Expert Review Panel</label>
        <referenceTo>Expert_Review_Panel__c</referenceTo>
        <relationshipLabel>Application Feedback</relationshipLabel>
        <relationshipName>Application_Feedback</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Application Feedback</label>
    <nameField>
        <displayFormat>AF-{000000}</displayFormat>
        <label>Application Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Attachment_Id__c</fullName>
        <description>Id of the actual/standard attachment, this is referenced in the view formula field</description>
        <label>Attachment Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expert_Review_Panel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert Review Panel</label>
        <referenceTo>Expert_Review_Panel__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stages__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stage</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Attachments</relationshipLabel>
        <relationshipName>Attachments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist for storing the type of document/attachment</description>
        <label>File Type</label>
        <picklist>
            <picklistValues>
                <fullName>1199 Direct Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval Forms</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Instructions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Articles of Incorporation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Auditor’s Statement Page</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Board of Directors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA Certification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Financial Report User Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Management Survey</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Statement Audit or SF-990</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Funding Certification Package</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Governing Body Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRS Certification of Non-Profit Status</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labor Union Concurrence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letters of Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>List of names of any funding organizations/sources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Logic Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Match Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Negotiated indirect cost agreement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organizational Chart</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recipient contact Form</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor/Project Director Position Description</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Supervisor&apos;s Resume</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Training Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Work Plan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1199 Direct Deposit Contact Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAE Waiver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AAE Waiver Request</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Attachment</label>
    <nameField>
        <label>Attachment Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attachments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Expert_Review_Panel__c.object
<CustomObject>
    <fields>
        <fullName>Panel_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Its a lookup to panel members object to select a panel member</description>
        <label>Panel Member</label>
        <referenceTo>Panel_Member__c</referenceTo>
        <relationshipLabel>Expert Review Panel</relationshipLabel>
        <relationshipName>Peer_Review_Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Panel__c</fullName>
        <label>Panel</label>
        <referenceTo>Paneling__c</referenceTo>
        <relationshipLabel>Expert Review Panel</relationshipLabel>
        <relationshipName>Expert_Review_Panel</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to contact object to find a reviewer</description>
        <label>Reviewer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Expert Review Panel</relationshipLabel>
        <relationshipName>Expert_Review_Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Expert Review Panel</label>
    <nameField>
        <displayFormat>ER-{000000}</displayFormat>
        <label>Peer Review Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expert Review Panel</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Panel_Application__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>it is a lookup to Application object to find particular Application</description>
        <label>Application</label>
        <referenceTo>Application3__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expert_Review_Panel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to Expert Review panel object to find an Expert Review Panel</description>
        <label>Expert Review Panel</label>
        <referenceTo>Expert_Review_Panel__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Paneling__c</fullName>
        <label>Paneling</label>
        <referenceTo>Paneling__c</referenceTo>
        <relationshipLabel>Panel Applications</relationshipLabel>
        <relationshipName>Panel_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Panel Application</label>
    <nameField>
        <displayFormat>PA-{000000}</displayFormat>
        <label>Panel Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Panel_Member__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to contact object to find an expert reviewer</description>
        <label>Expert Reviewer</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Expert Reviewer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Panel Members</relationshipLabel>
        <relationshipName>Panel_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Panel__c</fullName>
        <label>Panel</label>
        <referenceTo>Paneling__c</referenceTo>
        <relationshipLabel>Panel Members</relationshipLabel>
        <relationshipName>Panel_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to Reviewer pool object to find the reviewer</description>
        <label>Reviewer</label>
        <referenceTo>Reviewer_Pool__c</referenceTo>
        <relationshipLabel>Panel Members</relationshipLabel>
        <relationshipName>Panel_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Panel Member</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Panel Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Panel Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to stages object to the stage number</description>
        <label>Stage Number</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of the panel</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expert or Blended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <label>Stage Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Describes the type of that particular stage</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Internal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expert</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/CreatePanelAssignments.cls
public with sharing class CreatePanelAssignments
{
    private ApexPages.StandardController standardController;
 
    public CreatePanelAssignments(ApexPages.StandardController standardController)
    {
        this.standardController = standardController;
    }
 
    public PageReference AssignPanels()
    {
     PageReference pageRef = ApexPages.currentPage();
        // Apex code for handling record from a Detail page goes here
        Id recordId = standardController.getId();
        list<Attachment__c> attachmentsToAdd = new list<Attachment__c>();
        Paneling__c panel = [Select Id,Name,Stage_Number__c from Paneling__c where Id = :recordId];
        Stages__c stage = [Select s.Name, s.Id, (Select Id, Attachment_Id__c, Name, Description__c, Type__c, Stages__c From Attachments__r) From Stages__c s where Id = :panel.Stage_Number__c];
        
        Set<Id> PanelMembers = new Set<Id>();
        Set<Id> PanelApplications = new Set<Id>();
        map<Id,Id> reviewerIdtoPMId = new map<Id,Id>();
        List<Expert_Review_Panel__c> ExpertReviewPanels = new List<Expert_Review_Panel__c>();
        List<Application_Feedback__c> AppFeedbackList = new List<Application_Feedback__c>();
        
        /* Get a list of all of the Contacts associated with the panel */
        List<Panel_Member__c> panelMemberList = new List<Panel_Member__c>();
        panelMemberList = [SELECT Id,Expert_Reviewer__c FROM Panel_Member__c where Panel__c = :recordId];
        for(Panel_Member__c pm: panelMemberList){
          PanelMembers.add(pm.Expert_Reviewer__c);
          reviewerIdtoPMId.put(pm.Expert_Reviewer__c,pm.Id);
        }

        /* Get a list of all of the Applications associated with the panel */
        List<Panel_Application__c> panelApplicationList = new List<Panel_Application__c>();
        panelApplicationList = [SELECT Application__c FROM Panel_Application__c where Paneling__c = :recordId];
        for(Panel_Application__c pm: panelApplicationList){
          PanelApplications.add(pm.Application__c);
        }
        
        /* Create an Expert Reviewer Panel Object for each Reviewer */
        for (ID PanelMembersID: PanelMembers){
            Expert_Review_Panel__c exp = new Expert_Review_Panel__c();
            exp.Reviewer__c = PanelMembersID;
            exp.Panel__c = recordId;
            exp.Panel_Member__c = reviewerIdtoPMId.get(PanelMembersID);
            //Set the Status
            ExpertReviewPanels.add(exp);
        }
        insert ExpertReviewPanels;
        
        /* Create an Expert Reviewer Panel Object for each Reviewer */
        for (Expert_Review_Panel__c ExpertPanel: ExpertReviewPanels){
            for (ID ApplicationID: PanelApplications){
                Application_Feedback__c appFeedback = new Application_Feedback__c();
                appFeedback.Expert_Review_Panel__c = ExpertPanel.Id;
                appFeedback.Application__c = ApplicationID;
                //Need to add the Feedback Form
                AppFeedbackList.add(appFeedback);
            }  
        
        }
        insert AppFeedbackList;
        
        /*for(Expert_Review_Panel__c ExpertPanel: ExpertReviewPanels){
            if(stage.Attachments__r.size()>0){
                for(Attachment__c a: stage.Attachments__r){
                    Attachment__c newAttachment = new Attachment__c();
                    newAttachment.Name = a.Name;
                    newAttachment.Attachment_Id__c = a.Attachment_Id__c;
                    newAttachment.Expert_Review_Panel__c = ExpertPanel.Id;
                    newAttachment.Type__c = a.Type__c;
                    newAttachment.Description__c = a.Description__c;
                    newAttachment.RecordTypeId = Schema.SObjectType.Attachment__c.getRecordTypeInfosByName().get('Panel Attachment').getRecordTypeId();
                    attachmentsToAdd.add(newAttachment);
                }
            }
        }
        
        if(attachmentsToAdd.size()>0){
            insert attachmentsToAdd;
        }       */
        
        return null;
    }
    

}