retrieveUnpackaged/objects/Award_Reporting__c.object
<CustomObject>
    <fields>
        <fullName>Drawdowns_within_20_of_reported_OBG__c</fullName>
        <inlineHelpText>At the time of review, draw downs are within 20% of reported obligations</inlineHelpText>
        <label>Drawdowns within 20% of reported OBG</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FedShareUnliquidatedObligation_ThisPerio__c</fullName>
        <label>FedShareUnliquidatedObligation-ThisPerio</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Disabled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed and Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Re-work</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Submitted_Date__c</fullName>
        <label>Submitted Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Timely_Submission__c</fullName>
        <label>Timely Submission</label>
        <picklist>
            <picklistValues>
                <fullName>On time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Late</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_federal_share__c</fullName>
        <formula>Total_Federal_Funds_authorized__c + Federal_Share_of_unliquidated_obligation__c  +  Federal_Share_of_expenditures__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total federal share</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unobligated_balance_of_federal_funds__c</fullName>
        <formula>Total_Federal_Funds_authorized__c  -  Federal_Share_of_expenditures__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unobligated balance of federal funds</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Award Reporting</label>
    <nameField>
        <displayFormat>Award Reporting-{000}</displayFormat>
        <label>Award Reporting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Award Reporting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/AwardReportingHelper.cls
public with sharing class AwardReportingHelper {
    public static void lockFFR(map<Id,Award_Reporting__c> newMap, map<Id,Award_Reporting__c> oldMap){
    	Id ffrRTId = Schema.SObjectType.Award_Reporting__c.getRecordTypeInfosByName().get('Federal Financial Reports').getRecordTypeId();
    	map<String, Schema.SObjectField> awardReportfields= Schema.getGlobalDescribe().get('Award_Reporting__c').getDescribe().fields.getMap();
    	for(Id i:newMap.keyset()){
    		if(newMap.get(i).RecordTypeId == ffrRTId){
    			if((oldMap.get(i).Status__c == 'Submitted' && newMap.get(i).Status__c == 'Submitted') || (oldMap.get(i).Status__c == 'Re-submitted' && newMap.get(i).Status__c == 'Re-submitted')){    			
    				Award_Reporting__c oldRec = oldMap.get(i);
    				Award_Reporting__c newRec = newMap.get(i);
    				for(String s:awardReportFields.keyset()){
    					if(oldRec.get(s) != newRec.get(s)){    					  
    						newMap.get(i).addError('FFR cannot be edited when its submitted status');
    					}
    				}    				
    			}
    		}
    	}
    }
    
    public static void fieldUpdates(map<Id,Award_Reporting__c> newMap, map<Id,Award_Reporting__c> oldMap){
    	Id ffrRTId = Schema.SObjectType.Award_Reporting__c.getRecordTypeInfosByName().get('Federal Financial Reports').getRecordTypeId();
    	for(Id i:newMap.keyset()){
    		if(newMap.get(i).RecordTypeId == ffrRTId){
    			if((oldMap.get(i).Status__c != newMap.get(i).Status__c) &&  (oldMap.get(i).Status__c != 'Submitted' && newMap.get(i).Status__c == 'Submitted')){
    				Award_Reporting__c oldRec = oldMap.get(i);
    				Award_Reporting__c newRec = newMap.get(i);
    				if((newRec.Unobligated_balance_of_federal_funds__c/newRec.Total_federal_share__c) <= (0.2 * newRec.FedShareUnliquidatedObligation_ThisPerio__c))
    					newRec.Drawdowns_within_20_of_reported_OBG__c = 'Yes';
    				else
    					newRec.Drawdowns_within_20_of_reported_OBG__c = 'No';
    					
    				if(newRec.Submitted_Date__c <= newRec.Due_Date__c)
    					newRec.Timely_Submission__c = 'On-Time';
    				else
    					newRec.Timely_Submission__c = 'Late';    					
    				
    			} 
    		}
    	}
    }
}