retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>This field stores the Date of Birth of the user.</description>
        <inlineHelpText>This information is collected for demographic reporting purposes only and is not used to determine your eligibility to become an Expert Reviewer.</inlineHelpText>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Ethnicity_Type__c</fullName>
        <description>This information is collected for demographic reporting purposes</description>
        <inlineHelpText>This information is collected for demographic reporting purposes only and is not used to determine your eligibility to become an Expert Reviewer.</inlineHelpText>
        <label>Ethnicity Type</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Asian or Asian American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Other Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian or Asian American1</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>This information is collected for demographic reporting purposes</description>
        <inlineHelpText>This information is collected for demographic reporting purposes only and is not used to determine your eligibility to become an Expert Reviewer.</inlineHelpText>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>How_did_you_hear_about_CNCS_Reviews__c</fullName>
        <inlineHelpText>This information is collected for reporting purposes only and is not used to determine your eligibility to become an Expert Reviewer.</inlineHelpText>
        <label>How did you hear about CNCS Reviews?</label>
        <picklist>
            <picklistValues>
                <fullName>Email/recruitment flyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Listserv or Newsletter</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recommended by friend or colleague</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CNCS Website (NationalService.gov)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>If_Yes_describe_what_is_needed__c</fullName>
        <inlineHelpText>The information entered has no impact on selection or eligibility for participation in a Review, and is used for the sole purpose of providing reasonable accommodation to all participants.</inlineHelpText>
        <label>If Yes, describe what is needed.</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Is_this_a_Mobile_Number__c</fullName>
        <description>The user must be able to identify if the phone number is a mobile phone number</description>
        <label>Is this a Mobile Number</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_City__c</fullName>
        <description>This field stores mailing city of the user.</description>
        <label>Mailing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_State__c</fullName>
        <description>This field stores mailing state of the user</description>
        <label>Mailing State</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_Address_1__c</fullName>
        <description>This field stores the mailing address of the user.</description>
        <label>Mailing Street Address 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Street_Address_2__c</fullName>
        <description>This field stores the mailing address of the user</description>
        <label>Mailing Street Address 2</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mailing_Zip_Code__c</fullName>
        <description>This field stores the zip code of the user</description>
        <label>Mailing Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>This field stores the middle name of the user.</description>
        <label>Middle Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Please_Specify__c</fullName>
        <description>This field is required if &quot;other&quot;  is selected in the &quot;How did you hear about the CNCS Reviews&quot;.</description>
        <inlineHelpText>If &quot;Other&quot; is selected, Please specify</inlineHelpText>
        <label>Please Specify</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Race_Type__c</fullName>
        <inlineHelpText>This information is collected for demographic reporting purposes only and is not used to determine your eligibility to become an Expert Reviewer.</inlineHelpText>
        <label>Race Type</label>
        <picklist>
            <picklistValues>
                <fullName>American Indian or Alaska Native</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Asian or Asian American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Black or African American</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Native Hawaiian or Other Pacific Islander</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>White</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Re_Enter_Email__c</fullName>
        <label>Re-Enter Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Reasonable_Accommodations_Required__c</fullName>
        <inlineHelpText>Please select “Yes” if you require special accommodation, either to use the system or to work as an Expert Reviewer.</inlineHelpText>
        <label>Reasonable Accommodations Required?</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>State_of_Residence__c</fullName>
        <label>State of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <label>Suffix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Would_you_like_to_receive_texts__c</fullName>
        <label>Would you like to receive texts?</label>
        <picklist>
            <controllingField>Is_this_a_Mobile_Number__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/History__c.object
<CustomObject>
    <fields>
        <fullName>College_University__c</fullName>
        <inlineHelpText>CNCS staff uses the information in the following sections determine eligibilty to become a Review Participant, so be as comprehensive as possible.</inlineHelpText>
        <label>College/University</label>
        <type>TextArea</type>
    </fields>
    <label>History</label>
    <nameField>
        <displayFormat>ID-{000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>History</pluralLabel>
    <recordTypes>
        <fullName>Education</fullName>
        <active>true</active>
        <description>Child to User Account/Contact</description>
        <label>Education</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/ExpertApplicationFinal1.cls
public with sharing class ExpertApplicationFinal1 {

    public ExpertApplicationFinal1 () {

    }




    public ExpertApplicationFinal1 (ApexPages.StandardController controller) {
        
        con = new contact();
        hist = new History__c();
        hist1 = new History__c();
        
        attach = new Attachment(); 
        // Add more Contact to account
         abool =false;
         empbool =false;
         edubool =false;
    
      //  contacts = (Contact)controller.getRecord();
        delattendeeList = new List<History__c>();
        delattendees = new List<History__c>();
        
        
        addattendeeList = new List<History__c>();
        //addattendeeList.add(new History__c());
        
        empaddattendeeList = new List<History__c>();
      //  empaddattendeeList.add(new History__c());
        rend1=false;
         //Ends here
         // save as draft starts here
            educationLists =new List<History__c>();
            History__c dummyLogicModel = new  History__c();   
            educationLists .add(dummyLogicModel); 
            
            employementLists=new List<History__c>();
            History__c dummyLogicModel1 = new  History__c();   
            employementLists.add(dummyLogicModel1); 
            
            
          id=Apexpages.currentPage().getParameters().get('id');
           If(id!=null && id!=''){
            con =[SELECT AccountId,CreatedById,CreatedDate,Date_of_Birth__c,Ethnicity_Type__c,Fax,FirstName,Gender__c,
            HomePhone,How_did_you_hear_about_CNCS_Reviews__c,Id,If_Yes_describe_what_is_needed__c,Is_this_a_Mobile_Number__c,LastName,
            Mailing_City__c,Mailing_State__c,Mailing_Street_Address_1__c,Mailing_Street_Address_2__c,Mailing_Zip_Code__c,
            Middle_Name__c,Phone,Please_Specify__c,Primary_Phone__c,otherphone,Email,
            Race_Type__c,Reasonable_Accommodations_Required__c,Re_Enter_Email__c,Salutation,State_of_Residence__c,Suffix__c,
            Would_you_like_to_receive_texts__c FROM Contact where id=:id];
            system.debug('contact lst -->'+con);
          
            /*addattendeeList =[select id,name,Area_s_of_Study_Degree_Details__c,College_University__c,Degree_Earned__c,From__c,Highest_Level_of_Education__c,Organization_Type__c,To__c,User_Account__c from History__c where User_Account__c=:con.id];
            
            empaddattendeeList = [select id,name,Area_of_Expertise__c,Experience_Type__c,Expertise__c,From__c,Job_Description__c,Organization_Type__c,To__c,
            User_Account__c,Years_of_Experience__c from History__c where User_Account__c=:con.id];
            system.debug('employee lst-->'+empaddattendeeList);*/
           }
           

            // save as draft ends here  
       
        
    }
public String id;    
public ID acctID{get;set;}
public ID contactID{get;set;}
public string lastname{get;set;}
public History__c hist{get;set;}
public contact con{get;set;}
//set { con = new contact(); }}

public History__c hist1{get;set;}
public string accname{get;set;}
public Attachment attach{get; set;}  
public List<Attachment> attachList {get; set;}
// Add more Contact to account

public Account accounts;
public Contact contacts;
public History__c del;
public History__c empdel;
public boolean button_flag=false;
public boolean edubutton_flag=false;
public boolean empbutton_flag=false;
public List<History__c> addattendeeList {get;set;}
public List<History__c> empaddattendeeList {get;set;}
public List<History__c> delattendeeList {get;set;}
public List<History__c> empdelattendeeList {get;set;}
public List<History__c> attendeeList {get;set;}
public List<History__c> empattendeeList {get;set;}
public Integer totalCount {get;set;}
public Integer totalCount1 {get;set;}
public Integer rowIndex {get;set;}
public boolean abool{get;set;}
public boolean edubool{get;set;}
public boolean empbool {get;set;}
public Integer rowNum{get;set;}
public Integer rowNum1{get;set;}

public List<History__c> delAttendees {get; set;} 
public List<History__c> empdelAttendees {get; set;} 
Public Boolean rend1{get;set;}
//Ends here
// save as draft starts here
public Boolean displayMsg{get;set;}
Public String rectype{get;set;}
public List<History__c> educationLists {get; set;}
public List<History__c> employementLists {get; set;}

     //Save all the data to contact,education and employee object
    public pagereference save_upsert(){
           
       PageReference Redirect;
                
       if(con.Salutation== null ||con.Salutation=='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Salutation' );
            ApexPages.addMessage(myMsg); 
            return null;
         }
         
        
         if(con.FirstName == null ||con.FirstName=='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Firstname' );
            ApexPages.addMessage(myMsg); 
            return null;
         }
         
        
         if(con.LastName== null ||con.LastName=='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter LastName' );
            ApexPages.addMessage(myMsg); 
            return null;
         }  
          
         if(con.Primary_Phone__c== null ||con.Primary_Phone__c=='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Primary Phone' );
            ApexPages.addMessage(myMsg); 
            return null;
         }  
         if(con.Is_this_a_Mobile_Number__c == null ||con.Is_this_a_Mobile_Number__c=='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Is this a mobile number?' );
            ApexPages.addMessage(myMsg); 
            return null;
         } 
         if(con.Email == null ||con.Email=='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Email' );
            ApexPages.addMessage(myMsg); 
            return null;
         } 
         if(con.Re_Enter_Email__c == null ||con.Re_Enter_Email__c=='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Re-Enter Email' );
            ApexPages.addMessage(myMsg); 
            return null;
         } 
         if(con.Mailing_Street_Address_1__c == null ||con.Mailing_Street_Address_1__c =='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Mailing Address' );
            ApexPages.addMessage(myMsg); 
            return null;
         } 
         if(con.Mailing_State__c == null ||con.Mailing_State__c =='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Mailing State' );
            ApexPages.addMessage(myMsg); 
            return null;
         } 
         if(con.Mailing_City__c == null ||con.Mailing_City__c =='') 
         {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.ERROR,'You must enter Mailing city' );
            ApexPages.addMessage(myMsg); 
            return null;
         } 
               
         
            insert con;
            ID conID = con.ID;
            
            system.debug('name -->'+hist.name); 
            if(hist.name!='' && hist.name!=null)
            {   
            hist.User_Account__c= con.id;
            insert hist;
            }   
            
         
            system.debug('addattendeeListid-->'+addattendeeList);
            if(edubool==true)
            {
            for(History__c ed:addattendeeList){
                if(ed!=null )
                ed.User_Account__c=con.ID;
                system.debug('ed.User_Account__c-->'+ed.User_Account__c);
                
            }
             system.debug('addattendeeListid-->'+addattendeeList.size());
             
            
            insert addattendeeList;
            system.debug('addattendeeListid-->'+addattendeeList);
            }
           
         
            
            system.debug('Contact id-->'+hist1.User_Account__c);        
            if(hist1.name!='' && hist1.name!=null) 
            {
            hist1.User_Account__c= con.id;
            insert hist1;
            }
            if(empbool==true)
            {
            for(History__c em:empaddattendeeList){
                if(em!=null)
                em.User_Account__c=con.ID;
                system.debug('em.User_Account__c-->'+em.User_Account__c);
                
            }
             Insert empaddattendeeList;
            }
            attachList = new List<Attachment>();       
                     
             try
            {
            attachList.add(new Attachment(parentId = con.id, name= attach.name, body= attach.body));
            System.debug('attachList list @@@@@@@'+attachList);
            System.debug('empattendeeList list @@@@@@@'+empattendeeList);
            if(attachList.size()>0 && attachList[0].name!='' && attachList[0].body!=null)
            insert attachList;
            }
            catch(Exception e)
            {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.error,'Please attach a file in attachments section' );
            ApexPages.addMessage(myMsg); 
            return null;
            
            }
            finally {
            attach.name = null;
            attach.body = null;
            attach = new attachment();
            }
           
            //insert empattendeeList;   
              
       
       
       
        PageReference pageref = new PageReference('/'+con.id);
        return pageref ;
       
   }

    // Save as draft functionality Start from here

    Public PageReference SaveAsDraft()
    {
            System.debug('test save as draft');
            PageReference Redirect;

            try{
            System.debug('Save as draft try method');
            System.debug('Contact Id'+id);
            System.debug('Contact'+con);
     
            If(id!=null && id!='')
            {
            System.debug('Contact Id'+con.id);
            Redirect = new PageReference('/'+con.id);
            update con;
            System.debug('Contact-->'+con);
            return Redirect;
            }

            else{
            
           
            System.debug('Contact-->'+con.lastname);
            insert con;
            system.debug('Contact++'+con);
            Redirect = new PageReference('/'+con.id);
            System.debug('education list size'+educationLists.size());
            
            
            system.debug('Contact id-->'+hist.User_Account__c); 
            if(hist.name!='' && hist.name!=null)
            {
            hist.User_Account__c= con.id;    
            insert hist;
            }
           // if(educationLists.size()>0){       
            System.debug('addattendeeList list size'+addattendeeList.size());
             if(edubool==true)
             {
             for(History__c ed:addattendeeList){
                if(ed!=null)
                    ed.User_Account__c=con.ID;
                }
            
                insert addattendeeList;
             }
            displayMsg=True; 
            System.debug('education list-->'+educationLists);
            //}
            System.debug('employement list size'+employementLists.size());
            
            
            system.debug('Contact id-->'+hist1.User_Account__c); 
            if(hist1.name!='' && hist1.name!=null)
            {
                hist1.User_Account__c= con.id;
                insert hist1;
            }
        
            
            //if(employementLists.size()>0){       
            if(empbool==true)
            {
            for(History__c em:empaddattendeeList){
                if(em!=null)
                    em.User_Account__c=con.ID;
            }
            
                Insert empaddattendeeList;
            }
            displayMsg=True; 
            System.debug('employement list-->'+employementLists);
           // }
            
           /* if(attachList.size()>0){       
           
            For(attachment att:attachList){
            att.ParentId = con.id;
            att.name=att.name;
            att.body= attach.body;
            }
            Insert attachList;
            displayMsg=True; 
            }
            */
            attachList = new List<Attachment>();       
            
            
             try
            {
            attachList.add(new Attachment(parentId = con.id, name= attach.name, body= attach.body));
            System.debug('attachList list @@@@@@@'+attachList);
            System.debug('empattendeeList list @@@@@@@'+empattendeeList);
            if(attachList.size()>0 && attachList[0].name!='' && attachList[0].body!=null)
            insert attachList;
            }
            catch(Exception e)
            {
            ApexPages.Message myMsg = new  ApexPages.Message(ApexPages.Severity.error,'Please attach a file in attachments section' );
            ApexPages.addMessage(myMsg); 
            return null;
            
            }
            return Redirect;
            }
        }
            
            
            
            catch(Exception e){
            System.debug('@@@@@@@@!!!!!'+e.getmessage());
            }

            return null;

          
       }
       
   
       
  // Save as draft functionality ends here
  
  
  public void AddRow1()
    {
       
        edubool=true;
        addattendeeList.add(new History__c());
    }
    
    public void delRow1()
    {
        rowNum = Integer.valueOf(apexpages.currentpage().getparameters().get('index'));
        addattendeeList.remove(rowNum);   
    }  

    public void AddEmpRow1()
    {
        empbool=true;
        empaddattendeeList.add(new History__c());
    }
    
    public void delEmpRow1()
    {
        rowNum1 = Integer.valueOf(apexpages.currentpage().getparameters().get('index'));
        empaddattendeeList.remove(rowNum1);   
    }   
    
    
    
 
}