retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area_of_Expertise__c</fullName>
        <label>Area of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilitator/Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Expertise__c</fullName>
        <label>Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>Collaborated or partnered with one or more service programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service program funded by CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service program funded by a non-governmental organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service program funded by a state or local government agency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Managed a service-learning program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Participated in a service or service-learning program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adult Education &amp; Literacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>After School Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Civic Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community-Based</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Computer Literacy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (Higher Ed.)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education (K-12)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Elementary Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Faculty/teacher professional development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Work Study</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Head Start/School Preparedness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Professional Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Secondary Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Service Learning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring &amp; Child Literacy - Elementary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring &amp; Child Literacy - High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tutoring &amp; Child Literacy - Middle School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clean Energy Experience</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Community Restoration/Clean Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Energy Conservation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Natural Resource Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waste Reduction/Management/Recycling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wildlife, Land, Vegetation Protection/Restoration</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Highest__c</fullName>
        <description>This field pulls the highest level of education value from history object.</description>
        <label>Highest Level of Education</label>
        <picklist>
            <picklistValues>
                <fullName>High School Diploma/GED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associates Degree (AA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Degree (e.g. MA, PhD, MD, JD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical School/ Apprenticeship/ Vocational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Performance_Rating__c</fullName>
        <label>Performance Rating</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_of_Residence__c</fullName>
        <label>State of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the epert reviewer application</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - SAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Years_of_Experience__c</fullName>
        <description>This field value sums up the total experience of the applicant and is pulled from the History object .</description>
        <label>Years of Experience</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>perSequence__c</fullName>
        <displayFormat>{0}</displayFormat>
        <label>perSequence</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/NOFA_Group__c.object
<CustomObject>
    <fields>
        <fullName>Review_Type__c</fullName>
        <label>Review Type</label>
        <picklist>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expert or Blended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>NOFA Group</label>
    <nameField>
        <displayFormat>NOFA Group-{0000}</displayFormat>
        <label>NOFA Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NOFA Group</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Reviewer_Pool__c.object
<CustomObject>
    <fields>
        <fullName>Expert_Reviewer_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Expert Reviewer Name</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Expert Reviewer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reviewer Pools</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NOFA_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>NOFA Group</label>
        <referenceTo>NOFA_Group__c</referenceTo>
        <relationshipLabel>Reviewer Pools</relationshipLabel>
        <relationshipName>Reviewer_Pools</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Available with Comments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre-Confirmed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eligible – COI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Reviewer Pool</label>
    <nameField>
        <displayFormat>RP-{0000}</displayFormat>
        <label>Reviewer Pool Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviewer Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/AddReviewerPoolCont.cls
public class AddReviewerPoolCont {
    
    public string qryStr{get;set;}
    public List<contactWrapper> wrappedContacts {get; set;}
    public Contact con{get;set;}
    public decimal rating{get;set;}
    public decimal yrsofexp{get;set;}
    public set<Id> contactIdsfromPool = new set<Id>();
    public list<Contact> lContacts{get;set;} 
    public string debugsoql{get;set;}
    public NOFA_Group__c panel;
    public string lastName{get;set;}
    public String personId{get;set;}
    public String selectedstates{get;set;}
    public String selectedexpertise{get;set;}
    public String selectedareaofExpertise{get;set;}
    
    public AddReviewerPoolCont() {
        
        /*list<Reviewer_Pool__c> poolMembers = new list<Reviewer_Pool__c>();
        //String panelId = ApexPages.currentPage.getParameters.get('id');
        
        if(ApexPages.currentPage().getParameters().get('id')!=null)
            panel = [Select Id,Name,Review_Type__c,Status__c from NOFA_Group__c where Id = :ApexPages.currentPage().getParameters().get('id')];
            
        if(panel!=null)         
            poolMembers = new list<Reviewer_Pool__c>([Select Id,Expert_Reviewer_Name__c from Reviewer_Pool__c where Status__c = 'Available' ]);
        
        if(poolMembers.size()>0){   
            for(Reviewer_Pool__c r: poolMembers){
                contactIdsfromPool.add(r.Expert_Reviewer_Name__c);
            }
        }*/
        con = new Contact();
         //con =[Select Id,Name,Email,Area_of_Expertise__c,Expertise__c ,Years_of_Experience__c,Highest__c,Performance_Rating__c,State_of_Residence__c,Status__c from Contact where Id in :contactIdsfromPool and status__c='Accepted' ];
        
    }
    
    
    
    public List<contactWrapper> getContacts() {
        lContacts = new list<Contact>([Select Id,Name,Email,Area_of_Expertise__c,Expertise__c,Years_of_Experience__c ,Highest__c,Performance_Rating__c,State_of_Residence__c,Status__c from Contact where  status__c='Accepted' and RecordType.Name ='Expert Reviewer']);
        
        if(wrappedContacts == null) {
            wrappedContacts = new List<contactWrapper>();  
            for(Contact c: lContacts){
                wrappedContacts.add(new contactWrapper(c));
            }                     
        }
        return wrappedContacts;

    }

    public void runSearch(){
        system.debug('in search');
        string soql;
        /*string area = Apexpages.currentPage().getParameters().get('area');
        //string education = Apexpages.currentPage().getParameters().get('education');
        string status = Apexpages.currentPage().getParameters().get('status');
        string residence = Apexpages.currentPage().getParameters().get('residence');
        String  rating1= Apexpages.currentPage().getParameters().get('rating');
        String  yrsofexp1= Apexpages.currentPage().getParameters().get('yrsofexp');
        String  expertise= Apexpages.currentPage().getParameters().get('expertise');
        String  fName = Apexpages.currentPage().getParameters().get('fName');
        String  lName = Apexpages.currentPage().getParameters().get('lName');
        String  email = Apexpages.currentPage().getParameters().get('email');
        String  personId = Apexpages.currentPage().getParameters().get('personId');
        String highestEdu = Apexpages.currentPage().getParameters().get('highestEdu');
        */
        
        system.debug('states = '+selectedStates);
        
        string fname = '';
        if(con.FirstName != null)
       		fname = con.FirstName;     	     		
              
        string lname = lastName;
        
        string email = '';
        if(con.Email !=null)
        	email = con.Email;
        	
        string pId = personId;        
        
        string status = '';
        if(con.Status__c != null)
        	status = con.Status__c;  
        	      	
        string rating1 = '';
        if(con.Performance_Rating__c != null)
        	rating1 = string.valueOf(con.Performance_Rating__c);
        	
                         
        string yrsofexp1 = '';
        if(con.Years_of_Experience__c != null)
        	yrsofexp1 = string.valueOf(con.Years_of_Experience__c);    
        	    
        string highestEdu = '';
        if(con.Highest__c != null)
        	highestEdu = con.Highest__c;
        	
        string residence = '';
        if(selectedStates != null)
        	residence = selectedstates;
        	
        string area = '';
        if(selectedareaofExpertise != null)
        	area = selectedareaofExpertise;
        	
        string expertise = '';
        if(selectedexpertise != null)
        	expertise = selectedexpertise;
        
       
        
        if(rating1 !='' && rating1 != null) {
            rating  = decimal.Valueof(rating1);
        }
        else{
            rating = 0;
        }
       
        if(yrsofexp1 !='' && yrsofexp1 != null) {
            yrsofexp  = decimal.Valueof(yrsofexp1);
        }
        else{
            yrsofexp = 0;
        }
      
        string t1='\'';
        string t2= '\'';
        
       
        
       
         if((area =='' || area == null) && ( yrsofexp < 1) && (expertise =='' || expertise == null) && /*(education =='' || education == null) &&*/ (residence =='' || residence == null) && (status =='' || status == null) && rating < 1 && 
         	(fName == '' || fName == null) && (lName == '' || lName == null) && (email == '' || email == null) && (personId == '' || personId == null) && (highestEdu == '' || highestEdu == null))
        {
             soql = 'select Id,Name,firstname,lastname,Email,Area_of_Expertise__c,Expertise__c ,Years_of_Experience__c,Highest__c,perSequence__c,Performance_Rating__c,State_of_Residence__c,Status__c from contact where  status__c=\'Accepted\' and RecordType.Name =\'Expert Reviewer\'';     
        }
        else
        {
            soql = 'select Id,name,firstname,lastname,Email,Area_of_Expertise__c,Expertise__c ,Years_of_Experience__c,Highest__c,perSequence__c,Performance_Rating__c,State_of_Residence__c,Status__c from contact where  status__c=\'Accepted\' and RecordType.Name =\'Expert Reviewer\'' ;
            if (!fName.equals(''))
                soql += ' AND FirstName = '+t1+fName+t2;
            if (!lName.equals(''))
                soql += ' AND LastName = '+t1+lName+t2;
            if (!email.equals(''))
                soql += ' AND Email = '+t1+email+t2;
            if (!personId.equals(''))
                soql += ' AND perSequence__c = '+t1+pId+t2;                                          
            /*if (!education.equals(''))
                soql += 'AND  Highest__c = '+t1+education+t2;*/
      		if (!highestEdu.equals(''))
                soql += ' AND Highest__c = '+t1+highestEdu+t2;                 
            if (!status.equals(''))
                soql += ' AND Status__c = '+t1+status+t2;
                
             if (!residence.equals('')){
             	/*String[] tmpList = residence.split(',');
             	if(tmpList.size()==1){
             		soql += ' AND State_of_Residence__c = '+t1+tmpList[0]+t2;
             	}
             	if(tmpList.size()>1){
             		soql += 'AND ';             	
             		for(String s: tmpList){
             			soql += ' (State_of_Residence__c = '+t1+s+t2+' OR ';
             		}
             	}*/             	
             }
                      
            if (!area.equals(''))
                soql += ' AND Area_of_Expertise__c = '+t1+area+t2;                
            if (!expertise.equals(''))
                soql += ' AND Expertise__c = '+t1+expertise+t2;
            
            
            if(rating <1) {
                soql+='';
            }
            else {
                soql += ' AND Performance_Rating__c= '+rating;
            }
            
            if(yrsofexp <1) {
                soql+='';
            }
            else {
                soql += ' AND Years_of_Experience__c= '+yrsofexp;
            }
       
           system.debug('**************************************query'+soql);
            debugsoql = soql;
           
           
            //return wrappedContacts;
            
        
        }    
        
        if(lContacts.size()>0)
                lContacts.clear();
        lContacts = new list<Contact>();
        lContacts = database.query(soql);
            
        if(wrappedContacts.size()==0) {
            wrappedContacts = new List<contactWrapper>();  
            for(Contact c: lContacts){
                wrappedContacts.add(new contactWrapper(c));
            }                     
        }
        else if(wrappedContacts.size()>0){
            wrappedContacts.clear();
            wrappedContacts = new List<contactWrapper>();  
            for(Contact c: lContacts){
                wrappedContacts.add(new contactWrapper(c));
            }               
        }   
                
    }
    
    public class contactWrapper{
        public Contact con{get;set;}        
        public Boolean isSelected{get;set;}     
        
        public contactWrapper(Contact c) {
            con = c;
            isSelected = false;

        }
    }           
    
    public PageReference savePanelMembers(){
        list<Reviewer_Pool__c> newpanelMembers = new list<Reviewer_Pool__c>();
        set<Id> selectedContactIds = new set<Id>();
        for(ContactWrapper c: wrappedContacts){
            if(c.isSelected){
                selectedContactIds.add(c.con.Id);
            }
        }
        map<String,Reviewer_Pool__c> existingMembersMap = new map<String,Reviewer_Pool__c>();
        list<Reviewer_Pool__c> existingPanelMembers = new list<Reviewer_Pool__c>([Select Id,Expert_Reviewer_Name__c,NOFA_Group__c from Reviewer_Pool__c ]);
        for(Reviewer_Pool__c pm: existingPanelMembers){
            existingMembersMap.put(String.valueOf(pm.Expert_Reviewer_Name__c)+String.valueOf(pm.NOFA_Group__c),pm);
        }
        
        if(selectedContactIds.size()>0){
            for(Id i: selectedContactIds){
                String key = String.valueOf(i)+String.valueOf(panel.Id);
                system.debug('key = '+key);
                system.debug('map = '+existingMembersMap);
                if(existingMembersMap.get(key) == null){
                    Reviewer_Pool__c pm = new Reviewer_Pool__c();
                    pm.Expert_Reviewer_Name__c = i;
                    pm.NOFA_Group__c = ApexPages.currentPage().getParameters().get('id');
                    pm.Status__c = 'Active';
                    // pm.Reviewer__c = 
                    newpanelMembers.add(pm);
                }
            }
        }
        
        if(newpanelMembers.size()>0){
            insert newpanelMembers;
        }
        PageReference pg = new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
        return pg;
    }
    
    public PageReference cancel(){
        PageReference pg = new PageReference('/'+ApexPages.currentPage().getParameters().get('id'));
        return pg;
    }
	
	public List<SelectOption> stateslist{
		set;
		get{
			Schema.DescribeFieldResult Industryvalues = contact.State_of_Residence__c.getDescribe();

   		    List<Schema.PicklistEntry> Industryvalueslist = Industryvalues.getPicklistValues();

   		    List<SelectOption> options = new List<SelectOption>();
   			for(Schema.PicklistEntry c:Industryvalueslist)
   		    {

   			 System.debug('@@@@4'+c.getValue());    

    		 options.add(new SelectOption(c.getValue(),c.getValue())); 
		    }
		    return options;
		}
	}
	
	public List<SelectOption> expertiselist{
		set;
		get{
			Schema.DescribeFieldResult Industryvalues = contact.Expertise__c.getDescribe();

   		    List<Schema.PicklistEntry> Industryvalueslist = Industryvalues.getPicklistValues();

   		    List<SelectOption> options = new List<SelectOption>();
   			for(Schema.PicklistEntry c:Industryvalueslist)
   		    {

   			 System.debug('@@@@4'+c.getValue());    

    		 options.add(new SelectOption(c.getValue(),c.getValue())); 
		    }
		    return options;
		}
	}
	
	public List<SelectOption> areaofexpertiselist{
		set;
		get{
			Schema.DescribeFieldResult Industryvalues = contact.Area_of_Expertise__c.getDescribe();

   		    List<Schema.PicklistEntry> Industryvalueslist = Industryvalues.getPicklistValues();

   		    List<SelectOption> options = new List<SelectOption>();
   			for(Schema.PicklistEntry c:Industryvalueslist)
   		    {

   			 System.debug('@@@@4'+c.getValue());    

    		 options.add(new SelectOption(c.getValue(),c.getValue())); 
		    }
		    return options;
		}
	}
	
    /*String[] countries = new String[]{};
    List<String> pickValues=new List<String>();
    
    String[] countries1 = new String[]{};
    List<String> pickValues1=new List<String>();
    
    String[] countries2 = new String[]{};
    List<String> pickValues2=new List<String>();
    
    public String[] getCountries() {
    return countries;
    }
     
    public String[] getCountries1() {
    return countries1;
    }

    public String[] getCountries2() {
    return countries2;
    }
    
    public void setCountries(String[] countries) {
    this.countries = countries;
    }
    
     public void setCountries1(String[] countries1) {
    this.countries = countries1;
    }
    
     public void setCountries2(String[] countries2) {
    this.countries = countries2;
    }
    public List<SelectOption> getdoWork(){

    Schema.DescribeFieldResult Industryvalues = contact.Area_of_Expertise__c.getDescribe();

    List<Schema.PicklistEntry> Industryvalueslist = Industryvalues.getPicklistValues();

    List<SelectOption> options = new List<SelectOption>();
    for(Schema.PicklistEntry c:Industryvalueslist)
    {

    System.debug('@@@@4'+c.getValue());    

    options.add(new SelectOption(c.getValue(),c.getValue())); 

    }

    return options;
    }
    public List<SelectOption> getdoWork1(){

    Schema.DescribeFieldResult Industryvalues = contact.Expertise__c.getDescribe();

    List<Schema.PicklistEntry> Industryvalueslist = Industryvalues.getPicklistValues();

    List<SelectOption> options1 = new List<SelectOption>();
    for(Schema.PicklistEntry c:Industryvalueslist)
    {

    System.debug('@@@@4'+c.getValue());    

    options1.add(new SelectOption(c.getValue(),c.getValue())); 

    }

    return options1;
    }
    public List<SelectOption> getdoWork2(){

    Schema.DescribeFieldResult Industryvalues = contact.State_of_Residence__c.getDescribe();

    List<Schema.PicklistEntry> Industryvalueslist = Industryvalues.getPicklistValues();

    List<SelectOption> options2 = new List<SelectOption>();
    for(Schema.PicklistEntry c:Industryvalueslist)
    {

    System.debug('@@@@4'+c.getValue());    

    options2.add(new SelectOption(c.getValue(),c.getValue())); 

    }

    return options2;
    }*/

    
}