retrieveUnpackaged/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Area_of_Expertise__c</fullName>
        <label>Area of Expertise</label>
        <picklist>
            <picklistValues>
                <fullName>CNCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Facilitator/Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Human Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Public Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bill Test</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Highest__c</fullName>
        <description>This field pulls the highest level of education value from history object.</description>
        <label>Highest Level of Education</label>
        <picklist>
            <picklistValues>
                <fullName>High School Diploma/GED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Associates Degree (AA)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Degree (e.g. MA, PhD, MD, JD)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less Than High School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Some College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical School/ Apprenticeship/ Vocational</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Performance_Rating__c</fullName>
        <label>Performance Rating</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State_of_Residence__c</fullName>
        <label>State of Residence</label>
        <picklist>
            <picklistValues>
                <fullName>AA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>JM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>This field stores the status of the epert reviewer application</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending - SAI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/ContactSearchCTRL.cls
public class ContactSearchCTRL {

 public list<contact> contactlist{get;set;}
public decimal rating{get;set;}
 public string debugsoql{get;set;}
 public boolean txt{set;get;}
 
 
    public ContactSearchCTRL(ApexPages.StandardController controller) {
          contactlist = new list<contact>();
          contactlist = [select firstname,lastname,Area_of_Expertise__c,Highest__c,Performance_Rating__c,Status__c,State_of_Residence__c from contact];
    }

public void runsearch()
{
    string soql;
    string area = Apexpages.currentPage().getParameters().get('area');
    string education = Apexpages.currentPage().getParameters().get('education');
   string status = Apexpages.currentPage().getParameters().get('status');
    string residence = Apexpages.currentPage().getParameters().get('residence');
    String  rating1= Apexpages.currentPage().getParameters().get('rating');
if(rating1 !='') {
 rating  = decimal.Valueof(rating1);
   }
    else {
    rating = 0;}
    System.debug('test::'+rating);
  //Decimal.valueOf  
  
    string t1='\'';
    string t2= '\'';
    
   
    
   // if((area =='' || area == null) && (education =='' || education == null) && (status =='' || status == null) && (residence =='' || residence == null) && rating == 0 )
   
     if((area =='' || area == null) && (education =='' || education == null) && (residence =='' || residence == null) && (status =='' || status == null) && rating < 1)
    {
     soql = 'select firstname,lastname,Area_of_Expertise__c,Highest__c,Performance_Rating__c,State_of_Residence__c,Status__c from contact ';
     //soql = 'select firstname,lastname,Area_of_Expertise__c,Highest__c,Performance_Rating__c,Status__c,State_of_Residence__c from contact';
     
   
}
    else
    {
     soql = 'select firstname,lastname,Area_of_Expertise__c,Highest__c,Performance_Rating__c,State_of_Residence__c,Status__c from contact where lastname!='+t1+t2 ;
     if (!area.equals(''))
    soql += ' AND Area_of_Expertise__c = '+t1+area+t2;
    
    if (!education.equals(''))
   soql += 'AND  Highest__c = '+t1+education+t2;
  
 
   if (!residence.equals(''))
  soql += ' AND State_of_Residence__c = '+t1+residence+t2;
  
  if (!status.equals(''))
  soql += ' AND Status__c = '+t1+status+t2;
  if(rating <1) {
soql+='';
}
else {
   soql += ' AND Performance_Rating__c= '+rating;
}
    // run the query again
   // runQuery();
    //return null;
       system.debug('**************************************query'+soql);
    contactlist = database.query(soql);
    debugsoql = soql;
    
    }   
    //soql = 'select id,firstname, lastname,Area_of_Expertise__c,Highest__c,Performance_Rating__c,Status__c,State_of_Residence__c from contact where Area_of_Expertise__c='+t1+area+t2+' and Highest__c='+t1+education+t2+' and Performance_Rating__c='+rating+' and status__c='+status+' and State_of_Residence__c='+residence ;
  //  soql = 'select id,firstname, lastname,Area_of_Expertise__c,Highest__c,Performance_Rating__c,State_of_Residence__c from contact where Area_of_Expertise__c='+t1+area+t2+' and Highest__c='+t1+education+t2+' and Performance_Rating__c='+rating+'and State_of_Residence__c='+residence ;

    
 
}
}