retrieveUnpackaged/objects/Feedback_questions__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Scoring_Method__c</fullName>
        <label>Scoring Method</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number (1-100)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Factor Option</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Four Factor Option</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage_Question2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stage Question</label>
        <referenceTo>Stage_Question__c</referenceTo>
        <relationshipLabel>Feedback Questions</relationshipLabel>
        <relationshipName>Feedback_Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Feedback Question</label>
    <nameField>
        <displayFormat>FQ-{0000}</displayFormat>
        <label>Feedback questions id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Paneling__c.object
<CustomObject>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>It is a lookup to stages object to the stage number</description>
        <label>Stage Number</label>
        <referenceTo>Stages__c</referenceTo>
        <relationshipLabel>Paneling</relationshipLabel>
        <relationshipName>Panel</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Paneling</label>
    <nameField>
        <displayFormat>Panel-{00000000}</displayFormat>
        <label>Panel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Paneling</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Stage_Question__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It states whether the stage question is active or not.</description>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Allow_Comments__c</fullName>
        <defaultValue>true</defaultValue>
        <description>It states whether comments are allowed or not</description>
        <label>Allow Comments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>If_Yes_Comments_Required__c</fullName>
        <description>selects from a set of values and based on the values its controls allow comments field</description>
        <label>If Yes, Comments Required</label>
        <picklist>
            <controllingField>Allow_Comments__c</controllingField>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Questions are entered here</description>
        <label>Question?</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Reviewers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experienced Reviewers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Expertise Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Control Reviewers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Rater Reliability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Review Quality Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer A</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewer B</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Scoring_Method__c</fullName>
        <label>Scoring Method</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number (1-100)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yes/No</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Factor Option</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Four Factor Option</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Section__c</fullName>
        <description>It selects a value from set of values, which derives the section in the stages object</description>
        <label>Section</label>
        <picklist>
            <picklistValues>
                <fullName>Section 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Section 5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Weight__c</fullName>
        <description>Weight for that particular question is entered</description>
        <label>Weight</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Stage Question</label>
    <nameField>
        <displayFormat>Stage Question-{0000}</displayFormat>
        <label>Stage Question ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stage Question</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Stages__c.object
<CustomObject>
    <fields>
        <fullName>Roles__c</fullName>
        <description>Describe the roles of the particular stage.</description>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Panel Coordinator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alternate Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Reviewers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Experienced Reviewers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Targeted Expertise Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluation Reviewer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Editor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality Control Reviewers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inter-Rater Reliability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Review Quality Control</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff Reviewers</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Stage_Number__c</fullName>
        <label>Stage Number</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage_Question1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Stage Question</label>
        <referenceTo>Stage_Question__c</referenceTo>
        <relationshipLabel>Stages</relationshipLabel>
        <relationshipName>Stages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Stages</label>
    <nameField>
        <displayFormat>Stage-{0000}</displayFormat>
        <label>Stages ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Stages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/TestFeedback.cls
public class TestFeedback {
    Public Feedback_questions__c feedbackquestionInput{get;set;}   
    Public Id tempid;
    Public Stage_Question__c stagequestion {get;set;}
    public list<selectOption> availableList {get;set;}     
    public list<selectOption> chosenList {get;set;}
    Public Feedback_questions__c SQ{get;set;} 
    public List<Feedback_questions__c> FeedbackQuestionList {get;set;}
     //Public List<Feedback_questions__c> FeedbackQuestionList = new List<Feedback_questions__c>();
    public TestFeedback(ApexPages.StandardController standardController)
    {
        
    
    Id recordId = standardController.getId();
  //  List<Feedback_questions__c> FeedbackQuestionList = new List<Feedback_questions__c>();
    //Paneling__c panel = [Select Id,Name,Stage_Number__c from Paneling__c where Id = :recordId];
    // Stages__c stage = [Select Name, Id, Stage_Question1__c From Stages__c  where Id = :panel.Stage_Number__c];
    
    
    
    feedbackquestionInput = new Feedback_questions__c();
    chosenList =  new list<SelectOption>();
    tempid = standardController.getRecord().Id;
    //id=Apexpages.currentPage().getParameters().get('ID');
    System.debug('Valueofid'+tempid);
    //stagequestion =[SELECT   Active__c,Allow_Comments__c,If_Yes_Comments_Required__c,Question__c,Roles__c,Scoring_Method__c,Section__c,Weight__c 
   // from Stage_Question__c where id=:tempid];
    FeedbackQuestionList = [SELECT Id, Name, Question__c from Feedback_questions__c where Stage_Question2__c = :stagequestion.Id];                 
    }
    
   }