retrieveUnpackaged/objects/Risk_Indicator__c.object
<CustomObject>
    <fields>
        <fullName>Risk_Profile__c</fullName>
        <label>Risk Profile</label>
        <referenceTo>Risk_Profile__c</referenceTo>
        <relationshipLabel>Risk Indicators</relationshipLabel>
        <relationshipName>Risk_Indicators</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Score__c</fullName>
        <formula>Score__c  * Weight__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Risk Indicator</label>
    <nameField>
        <displayFormat>RI-{000000}</displayFormat>
        <label>Risk Indicator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Indicators</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/objects/Risk_Profile__c.object
<CustomObject>
    <description>Project 7</description>
    <fields>
        <fullName>Risk_Score__c</fullName>
        <description>Need to update using a trigger - Roll up summary - Sum of Total Score on Risk Indicators</description>
        <label>Risk Score</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Risk Profile</label>
    <nameField>
        <displayFormat>RP-{0000000}</displayFormat>
        <label>Risk Profile Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Risk Profiles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

retrieveUnpackaged/classes/RiskIndicatorHelper.cls
public with sharing class RiskIndicatorHelper {
	public static void rollUpScore(map<Id,Risk_Indicator__c> newMap,map<Id,Risk_Indicator__c> oldMap){
		
		system.debug('newmap = '+newMap);
		system.debug('oldmap = '+oldMap);
		set<Id> parentIds = new set<Id>(); 
		if(oldMap == null){
			//after insert
			for(Id i: newMap.keyset()){
				parentIds.add(newMap.get(i).Risk_Profile__c);
			}
		}else{
			//after update
			if(newMap!=null){
				for(Id i:newMap.keyset()){
					if(newmap.get(i).Total_Score__c != null && (oldMap.get(i).Total_Score__c != newMap.get(i).Total_Score__c)){
						parentIds.add(newMap.get(i).Risk_Profile__c);
					}
				}
			}else{
				for(Id i:oldMap.keyset()){					
					parentIds.add(oldMap.get(i).Risk_Profile__c);					
				}
			}
		}
		
		list<Risk_Profile__c> parentProfiles = new list<Risk_Profile__c>([Select r.Risk_Score__c, r.Name, r.Id, (Select Id, Total_Score__c,Risk_Profile__c  From Risk_Indicators__r) From Risk_Profile__c r where Id in :parentIds]);
		Map<Id, Decimal> parentValues = new Map<Id, Decimal>();
		if(parentProfiles.size()>0){
			for(Risk_Profile__c rp: parentProfiles){
				if(rp.Risk_Indicators__r.size()>0){
					for(Risk_Indicator__c ri: rp.Risk_Indicators__r){
						if(parentValues.keySet().contains(ri.Risk_Profile__c) && ri.Risk_Profile__c  != null && ri.Total_Score__c != null)
		           		{
		                	Decimal tmp = parentValues.get(ri.Risk_Profile__c);
		                	tmp += ri.Total_Score__c;
		                	parentValues.put(ri.Risk_Profile__c, tmp);
		            	}
		            	else
		            	{
		               		if(ri.Total_Score__c != null){
		                  		parentValues.put(ri.Risk_Profile__c, ri.Total_Score__c);
		                	}
						}
					}
				}
				if(parentValues.get(rp.Id)!=null){
	                rp.Risk_Score__c = parentValues.get(rp.Id);
	            }else{
	                rp.Risk_Score__c = 0;
	            }    
				
		    }
		    system.debug('parentProfiles = '+parentProfiles);
		    update parentProfiles;
		}
	}
}